### ISSUE TITLE
Packaging -> Need a tagged version

### ISSUE THREAD

**Issue by SylvainCorlay** [zeromq/cppzmq#108]
As per discussion on https://github.com/zeromq/cppzmq/pull/107, I would like to package cppzmq for conda, it would be very nice to have a tagged version on GitHub, to have a fixed version of the code to refer to.

One thing that would help is that the tag always follow the same pattern and can be completely deduced from the version number. (typically `M.m.p`).

**Comment by JohanMabille** [comment]
That would really help with packaging.

**Comment by bluca** [comment]
Still not 100% sure it makes sense to tag this repository, but if it helps some use cases don't see why not. Pushed v4.2.1 to make it match libzmq

**Comment by SylvainCorlay** [comment]
Awesome. This is for the reproducible builds of conda-forge.

**Comment by SylvainCorlay** [comment]
@bluca FYI, cppzmq has been packaged for `conda`:

`conda install cppzmq -c conda-forge`

**Comment by bluca** [comment]
Fantastic, thank you very much for your work!

**Comment by SylvainCorlay** [comment]
We have also packaged zeromq 4.2.1 with the cmake install files by applying
the latests fixes as patches on the top of 4.2.1.

**Comment by SylvainCorlay** [comment]
Quick note on the packaging as we just updated the conda packages for `zeromq` and `cppzmq`: `cppzmq 4.2.2` works fine with `zeromq 4.2.3`, which is just a patch release. I think it makes sense for the version numbers of the two packages to be decorrelated and have a clear dependency requirement on zeromq, i.e.

`cppzmq 4.2.2 depends on zeromq >=4.2.1,<4.3.0`...

or every single patch release of zeromq will require a corresponding cppzmq release, and you won't be able to make releases for cppzmq only.
