### ISSUE TITLE
FindZeroMQ.cmake

### ISSUE THREAD

**Issue by abbradar** [zeromq/cppzmq#110]
Currently (in 4.2.1) cppzmq requires ZeroMQ module in CMake -- however, needed module is not bundled nor it can be found in libzmq distribution. Where should one take it from? Sorry if I have just overlooked something.

**Comment by bluca** [comment]
It should no longer be necessary but I'm not a CMake expert. @JohanMabille any idea?

**Comment by JohanMabille** [comment]
If you install cppzmq via cmake, you need to do the same with [libzmq](https://github.com/zeromq/libzmq)

Here is the command line for a minimal build and installation of libzmq:

```sh
cmake -D WITH_PERF_TOOL=OFF -D ZMQ_BUILD_TESTS=OFF -D ENABLE_CPACK=OFF
-D CMAKE_BUILD_TYPE=Release
make
make install
```

**Comment by abbradar** [comment]
I did this but cmake modules were not installed. A quick search haven't shown anything similar in libzmq source distribution either. Where are they located? 
-- 
Nikolay.

**Comment by JohanMabille** [comment]
They should be generated by the `make install` and the ZeroMQConfig.cmake.in file. It seems this file is available on master but not v4.2.1. Do you have the same issue with the master branch of libzmq ?

**Comment by qzhang41** [comment]
Sir can you tell me where i go wrong? I build cppzmq and libzmq with cmake but it show the following erro:
CMake Error at D:/working this semester/libzmq-master1/ZeroMQConfig.cmake:19 (message):
  File or directory D://include referenced by variable ZeroMQ_INCLUDE_DIR
  does not exist !
Call Stack (most recent call first):
  D:/working this semester/libzmq-master1/ZeroMQConfig.cmake:36 (set_and_check)
  CMakeLists.txt:4 (find_package)

**Comment by SylvainCorlay** [comment]
@abbradar did you specify the `CMAKE_INSTALL_PREFIX` when installing libzmq and zeromq.

**Comment by abbradar** [comment]
Sorry for the late response. @JohanMabille is right -- file isn't present in ZeroMQ 4.2.1 but it's there in master (so master works for me).
