### ISSUE TITLE
zmq::send always releases its message

### ISSUE THREAD

**Issue by keith-dev** [zeromq/cppzmq#112]
As a _messages_t_ is an object, it'll be release anyway. So unless the message content is being moved, I can't see the benefit of _zmq_send_ releasing the message.

In the case of creating a device that repeats a message to more than one destination socket, zmq_send_const must be called directly to stop the message from being released.

Can anyone explain why _zmq_send_ behaves this way and why _zmq_ should have a _send_const_ member?

**Comment by keith-dev** [comment]
The implementation of zmq_send_const is kind of pointless.  It constructs a message internally, uses it, and allows it to be destroyed.

I believe this is a poor implementation as it isn't really const as advertised.  And thus this mess shouldn't be pushed into the C++ interface.

I am closing this ticket.

**Comment by hun-nemethpeter** [comment]
I think you misread the code. The `zmq_send_const`

```
    zmq_msg_t msg;
    int rc = zmq_msg_init_data (&msg, (void *)buf_, len_, NULL, NULL);


```
but the zmq_send

```
   zmq_msg_t msg;
    if (zmq_msg_init_size (&msg, len_))
        return -1;

    //  We explicitly allow a send from NULL, size zero
    if (len_) {
        assert (buf_);
        **memcpy (zmq_msg_data (&msg), buf_, len_);**
    }
```

So the `zmq_send` do a complete copy with malloc + memcpy but the `zmq_send_const` just use a buf and len values for sending. There is a huge performance difference between the two version.

**Comment by hun-nemethpeter** [comment]
@yerden The sending will happen on an other thread. So you are just queuing the message. With `zmq_send` you can quckly assemble a message (even on the stack) and put it to the queue and then move on, releasing that message on your thread. The sending thread will release the copy of that message when it not needed anymore. In case of `zmq_send_const` you have to keep in memory the original message until the sending moment. And you have to find out when it happens somehow.
