### ISSUE TITLE
no longer compatible with zeromq/zermq4-x 

### ISSUE THREAD

**Issue by jgornowich** [zeromq/cppzmq#113]
Not sure if this c++ bindings should be compatible with zeromq4-x legacy stable release, but I am using zeromq 4.0.8 and cppzmq will no longer compile because method zmq_msg_gets() does not exist for reference in zmq.hpp:

https://github.com/zeromq/cppzmq/blob/master/zmq.hpp#L376

This may be as simple as changing the VERSION that is referenced in preprocessor directive?

I plan on upgrading to the zeromq/libzmq core engine soon, but I see a use to keep this compatible with legacy stable releases.

Also, are there any plans to create tags for this repo that somehow denote the compatible zeromq library version?  Maybe at least a couple that denote compatibility with the two legacy releases 4.0.x and 4.1.x?

**Comment by bluca** [comment]
That ifdef should probably be:

```#if ZMQ_VERSION >= ZMQ_MAKE_VERSION(4, 1, 0)```

instead. Could you please send a PR to fix it?

**Comment by bluca** [comment]
Merged, thank you!
