### ISSUE TITLE
2 Router-Dealer proxies do not work

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [zeromq/cppzmq#115]
Simply put, whichever proxy is first then the related processes work fine. The second one is ignored. For instance:

`zmq::proxy(m_frontEnd, m_backEnd, 0);
  zmq::proxy(m_frontEnd2, m_backEnd2, 0);`

I have a server with multiple threads listening for different connection points. All services listening for messages on the proxy m_frontEnd and m_backEnd work fine. The one using m_frontEnd2, m_backEnd2 never receive messages. 

If I swap the order:

`zmq::proxy(m_frontEnd2, m_backEnd2, 0);
  zmq::proxy(m_frontEnd, m_backEnd, 0);`

Now all services not recieving messages before are working fine and the services listening for messages on the proxy m_frontEnd and m_backEnd never receive messages.

The docs imply that we can have multiple proxies. This isn't the case or is a bug. 

I'm unsure which cppzmq version I'm using and the headers show support for cmake zmq over 4.1.0 and I'm using czmq 4.0.2 if that helps

**Comment by bjovke** [comment]
Well, you just can't start two proxies like that.
zmq::proxy() is a blocking call. It will not return until sockets and/or their context is deleted.
Only first of your proxies is started.
If you want to run two proxies at the same time you need to run them in different threads.

**Comment by TheMaverickProgrammer** [comment]
This was quite some time ago. Further research discovered what you said: it's a blocking function. Not clear at face value. How would you terminate them properly?

**Comment by bjovke** [comment]
You have to launch proxies in different threads.
Then you have three options to terminate them:

- Use `zmq::proxy()` with control socket (proxy_steerable) and send "TERMINATE" message to it.
- Delete context.
- Kill proxy thread (not recommended).
