### ISSUE TITLE
Issue with no NULL-terminated strings.

### ISSUE THREAD

**Issue by mikepeon-imdea** [zeromq/cppzmq#116]
Sender written in Python, receiver in C++.
recv() does not place an ending NULL after the received number of bytes but, as it does not return the number of bytes, it's not possible to do outside, either.
Result: Impossible to determine the end of the received string. It's just the example on strings on ZMQ tutorial for C.
The only solution seems to avoid the C++ port and use the underlying C functions, which return the length of the message. This method works perfectly with the Python sender.
Is this on purpose or a bug?
In this case, it's not possible to modify the Python sender to include the string length in the message itself.

**Comment by bjovke** [comment]
ZeroMQ does not NULL-terminate strings.
It doesn't know anything about the content of your message, it just sends/delivers it.
Read the documentation: [A-Minor-Note-on-Strings](http://zguide.zeromq.org/page:all#A-Minor-Note-on-Strings).

There are two things that you can do:

- Send additional 0 byte after the string from Python.
- It's not true that it's impossible to determine the end of string in C++ port. You have two recv() functions:
```
        inline size_t recv (void *buf_, size_t len_, int flags_ = 0);
        inline bool recv (message_t *msg_, int flags_ = 0);
```
First one returns the size of received data and second one stores the message in `zmq::message_t` object. You can then call `data()` and `size()` methods of `zmq::message_t` to retrieve your message and it's length.

I see no issue here.

**Comment by bjovke** [comment]
@mikepeon-imdea Did you manage to resolve the issue you had?

**Comment by mikepeon-imdea** [comment]
Yes, thanks for following up (I forgot to close the issue). I just switched to the C version and used zmq_recv(). I guess somehow I missed the size_t returned by the first function, as you explained afterwards.

**Comment by bjovke** [comment]
@mikepeon-imdea  Thank you for the information.
