### ISSUE TITLE
cmake install TARGETS given no ARCHIVE DESTINATIOn for static library target "cppzmq"

### ISSUE THREAD

**Issue by egberts** [zeromq/cppzmq#121]
From the master ([0feae8c](https://github.com/zeromq/cppzmq/commit/0feae8c3e907531395466b3871203fe0faddbe54)) , and using cmake v2.8.12.2 on CentOS 6.9, I clone and immediately did:

    cmake .

and get the following error message:

    --cppzmq v4.2.3
    CMake Error at CMakeLists.txt:30 (install):
      install TARGETS given no ARCHIVE DESTINATION for static library target "cppzmq".

    -- Configuring incomplete, errors occurred!

No idea how to fix that.  Stackoverflow wasn't helpful there either.

**Comment by matthewOConnell** [comment]
Having this same issue on CentOS 6.9.  Ran it through a git bisect.  Looks like it was broken with aa850e7ec29e8a87c53bd748642c87111584dd1c

**Comment by bluca** [comment]
@stefanherbrechtsmeier could you please have a look?

**Comment by herbrechtsmeier** [comment]
The CMake version 2.8.12 don't support `INTERFACE` libraries. If the version is below 3.0 we have to avoid this feature and act different inside the CMake files.

**Comment by ax3l** [comment]
We should just push the `cmake_minimum_required(VERSION 2.8.12)` line then to `3.0.0` to reflect that.
