### ISSUE TITLE
Is there a "shadow context"

### ISSUE THREAD

**Issue by eplumer** [zeromq/cppzmq#122]
I have a Java application using the JeroMQ project. At one point, it creates a sub-thread and initializes it with a "shadow context" for thread safety. Something like

  ZContext shadowCtx = ZContext.shadow( mainCtx );

I am porting this application to a C++ version based on CPPZMQ classes, esp. zmq::context_t.

I am not finding the equivalent idea of a shadow context. Does that exist for C++ applications. Can anyone point me at an example?

**Comment by sigiesec** [comment]
I don't really understand what a shadow context might be. The context_t is thread-safe in the sense that you can create/use socket_t's in different threads.

**Comment by eplumer** [comment]
Possibly, no such construct is needed in C++. JeroMQ documents this as needed when spinning up another thead which should get the shadow context instead of real one. Argument made is that sockets created within one context cannot be accessed by different threads

**Comment by sigiesec** [comment]
For all I know this is not necessary with libzmq. I will close the issue for now, feel free to reopen if you encounter any problems.
