### ISSUE TITLE
4.2.2 Release

### ISSUE THREAD

**Issue by ax3l** [zeromq/cppzmq#136]
@bluca with the last build updates and the last release being 6 months and 27 PRs old - are you planning a 4.2.2 release? :)

**Comment by ax3l** [comment]
@bluca sorry for being so persistent, just pinging you about a new revision release for `cppzmq` :)

**Comment by bluca** [comment]
Sorry, forgot about it, pushed a tag just now.

**Comment by bluca** [comment]
Would you like to help and compile a quick changelog for the rel page?
This is the diff: https://github.com/zeromq/cppzmq/compare/v4.2.1...master

Just listing the main visible changes would be enough.

**Comment by ax3l** [comment]
Sure, here it is:

### Bug Fixes

- `monitor_t`:
  - build error in constructor #135
  - blocked when used without threads #134
  - move constructor was only partly initialized #130
- `socket::send()`: improper `EHOSTUNREACH` handling #125
- CMake: 3.0+ is required #121 
- `ZMQ_MAKE_VERSION`: check against `zmq_msg_gets` did not properly exclude libzmq 4.0.X #114

## Features

- CMake:
  - export targets to config #118
  - pkg-config fallback for `libzmq` installs via autotools #133
- `peekstr` & `peektyp`: peek into parts of messages #124 
- allow empty handler parameter in `zmq::poller_t::add()` #119 #120
- `poller_t` class based on new libzmq poller API #111

## Misc

- install instructions added #129
- Copyright years updated d9f0f016c07046742738c65e1eb84722ae32d7d4
- typo in install instructions fixed #131

**Comment by ax3l** [comment]
@bluca description updated

**Comment by bluca** [comment]
Great, thanks, attached to the rel https://github.com/zeromq/cppzmq/releases/tag/v4.2.2
