### ISSUE TITLE
usage of deprecated destroy/term API functions and context shutdown

### ISSUE THREAD

**Issue by ovanes** [zeromq/cppzmq#137]
As docs for version 3.x and 4.x point out usage of `zmq_ctx_destroy` is deprecated by `zmq_ctx_term`.

Not sure if that thread on Python behaviour and general excurse to C API is of help:

https://lists.zeromq.org/pipermail/zeromq-dev/2014-June/025976.html

From this thread it seems like `zmq_ctx_destroy` behaves differently than the `zmq_ctx_term`. In addition, I end up from my part doing smth like:

```
      void shutdown()
      {
        if(interrupted_) return;
        interrupted_ = true;

        auto raw_context =static_cast<void*>(*context_ptr_);
        context_ptr_->close();

        zmq_ctx_shutdown(raw_context);
      }
```

The problem here is that, after a call to `zmq::context_t::close` the internal pointer of zmq::context_t is set to `NULL` which gives no room to call API's `shutdown` function and forces the caller to retrieve the internal context pointer first.

**Comment by bluca** [comment]
zmq_term and zmq_ctx_destroy both just call zmq_ctx_term for backward compatibility: https://github.com/zeromq/libzmq/blob/master/src/zmq.cpp#L237

It's right to use destroy here, to be compatible with older versions.

And you should _NOT_ call shutdown after term/destroy, as they de-allocate and mark the context as dead.
The shutdown is simply a subset of term/destroy, as in it does a subset of the operations of the latter, namely signal sockets for termination.
