### ISSUE TITLE
CMake Can't Include ZMQ with Dynamically Linked Libraries

### ISSUE THREAD

**Issue by Yareeve** [zeromq/cppzmq#143]
I'm trying to use cppzmq in a project created from CMake. First off, it's strange that CMake complains that I need ZeroMQ_DIR defined in addition to cppzmq_DIR (both of which must contain .cmake config files). Secondly, when I attempt to link to the regular cppzmq_LIBRARY (provided by the cppzmqConfig.cmake file), I get the following error:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
libzmq

In addition, no matter if I use static or dynamic linking, I get the following warning:
CMake Warning (dev) at C:/Program Files/ZeroMQ/share/cmake/ZeroMQ/ZeroMQTargets.cmake:54 (add_library):
  ADD_LIBRARY called with SHARED option but the target platform does not
  support dynamic linking.  Building a STATIC library instead.  This may lead
  to problems.
Call Stack (most recent call first):
  C:/Program Files/ZeroMQ/share/cmake/ZeroMQ/ZeroMQConfig.cmake:44 (include)
  C:/Program Files/cppzmq/share/cmake/cppzmq/cppzmqConfig.cmake:44 (find_package)
  CMakeLists.txt:39 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

Installed ZeroMQ and cppzmq according to instructions in cppzmq readme.

**Comment by Yareeve** [comment]
OK I was able to clean up some of this... If I place the cmake's "project()" directive before the "find_package(cppzmq)" call, I am able to get rid of the above error. In addition, I don't need to define ZeroMQ_DIR or cppzmq_DIR own my own--CMake is able to figure this out. However, I still can't use the ${cppzmq_LIBRARY} variable, which should be defined for me. I get the following error:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
libzmq

I should note that the statically linked library still works great. As of now, my code is as follows:

# Set the minimum required version of CMake
cmake_minimum_required( VERSION 3.6.2 )

# Create project.
project( MyProject)

# Choose whether we will use statically or dynamically linked libraries
set( DO_STATIC_LINKING	False)

if( DO_STATIC_LINKING )
	message (STATUS "Employing statically linked libraries" )
else( DO_STATIC_LINKING )
	message (STATUS "Employing dynamically linked libraries" )
endif( DO_STATIC_LINKING )

######################################################################
# Set up ZeroMQ
# TODO: get dynamic linking with ZeroMQ going
######################################################################

# Find ZMQ package and define the correct ZMQ library to use.
# Note: Statically linked library requires explicit inclusion of some of 
# the windows sockets libraries (wsock32.lib, ws2_32.lib, and Iphlpapi.lib)
find_package(cppzmq REQUIRED)
if( DO_STATIC_LINKING )
	set (ZMQ_LIBRARY ${cppzmq_STATIC_LIBRARY} wsock32.lib ws2_32.lib Iphlpapi.lib)
else( DO_STATIC_LINKING )
	set (ZMQ_LIBRARY ${cppzmq_LIBRARY} )
endif( DO_STATIC_LINKING )
message (STATUS "Using ZMQ library ${ZMQ_LIBRARY}" )

# Include ZMQ directories. Inclusion of both regular C ZeroMQ and C++ ZeroMQ
# include files is required for compilation.
include_directories(${cppzmq_INCLUDE_DIR} ${ZeroMQ_INCLUDE_DIR})

**Comment by sigiesec** [comment]
You can now find an example dependent project in the demo directory. Please have a look at that.

I am closing this issue for now. Please reopen if you still have problems, providing more information on what you are doing (how you installed libzmq and cppzmq, in which version).
