### ISSUE TITLE
libzmq 4.2.3 doesnt have ZMQ_EVENT_HANDSHAKE_FAILED definition

### ISSUE THREAD

**Issue by bingoko** [zeromq/cppzmq#147]
The libzmq 4.2.2 has ZMQ_EVENT_HANDSHAKE_FAILED, while 4.2.3 doesn't contain ZMQ_EVENT_HANDSHAKE_FAILED. And the zmq.hpp in cppzmq still invoke ZMQ_EVENT_HANDSHAKE_FAILED which causes a compilation failure.

**Comment by bluca** [comment]
DRAFT APIs are subject to change without notice, at some point it will be updated here too, you can build without DRAFTs in the meanwhile
