### ISSUE TITLE
Handling of EHOSTUNREACH

### ISSUE THREAD

**Issue by sigiesec** [zeromq/cppzmq#148]
I suggest to revert #125, which changed the handling of EHOSTUNREACH errors on zmq_send (on a ROUTER socket).

I don't think it is a good idea to use the same return value (false) for two different errnos (EAGAIN and EHOSTUNREACH). One major point of the cppzmq wrapper is to map the errno-based error handling to and exception-based error handling. A user of cppzmq does not expect to care about zmq_errno. #125 breaks this expectation. 

It makes sense not to use an exception for the EAGAIN case, since this is a normal result when you are performing a non-blocking operation.

**Comment by sigiesec** [comment]
In addition, #125 broke the existing behavior, which our code relied on.

**Comment by bluca** [comment]
Makes sense. Could you please send a PR?
