### ISSUE TITLE
Problem in using cppzmq/zmqlib shared libraries [.so's] in my project

### ISSUE THREAD

**Issue by jay11ca39** [zeromq/cppzmq#151]
Hello All,

I want to use the cpp binding of zeroMQ in my application. 
I have followed the instructions given in the README file.

1. Taken the latest code of libzmq: **https://github.com/zeromq/libzmq**
    and build it using:
```
    mkdir build 
    cd build
    cmake ..
    sudo make -j4 install
```

2. Taken the latest code of: **https://github.com/zeromq/cppzmq**
     and build it using:

```
    mkdir build 
    cd build
    cmake ..
    sudo make -j4 install
```

After that I can see  in the build folder there are different cmake files created. But I want to use required shared libraries directly in my application, as I am not using the make as my build system.

To make it simple:
1. What are the shared libraries will be generated.
2. How to generate them.
3. how can I use them in my application.

**Comment by bluca** [comment]
The shared library is installed by the libzmq repository, cppzmq is just a header that you include in your project.

If you are on Linux, consider using packages to install libzmq as it will make your life much easier:

http://zeromq.org/intro:get-the-software

On OSX you can use homebrew which is easy as well.

**Comment by jay11ca39** [comment]
Hi @bluca ,
Thanks for quick response.

(1) As per your comments In a linux machine:
```
echo "deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/ ./" >> /etc/apt/sources.list
wget https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/Release.key -O- | sudo apt-key add
apt-get install libzmq3-dev
```

It will install the libzmq.so in my system.
Then I can just include this header files:
zmq.hpp
zmq_addon.hpp

in my project and can build it and use zmq APIs right?

(2) But how about directly using the libzmq library.
     - My project is cpp based.
     - but i can just include the libzmq.so and can call zmq c apis from my c++ sdk?
      Will there be any problem.

**Comment by bluca** [comment]
1) Yes

2) Yes you can just use libzmq's C APIs If you don't want to use cppzmq. In that case, in your source files, use ```#include <zmq.h>``` and then link your application. How to do that depends on your build system, in general it's better to use pkg-config: http://zeromq.org/bindings:c

**Comment by jay11ca39** [comment]
Thanks @bluca 
I have verified as you said.
I am able to include the .so in my application.

**Comment by jay11ca39** [comment]
@bluca ,
I have one more question:
If I follow the below:

```
echo "deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/ ./" >> /etc/apt/sources.list
wget https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/Release.key -O- | sudo apt-key add
apt-get install libzmq3-dev

```

Which version of library it will install. for example: libzmq-3.0 or something else?

**Comment by bluca** [comment]
The latest, 4.2.2. you can find release notes on libzmq GitHub repo https://github.com/zeromq/libzmq/releases

**Comment by jay11ca39** [comment]
Thanks @bluca.
I got confused with name : apt-get install libzmq3-dev 
I thought it will install some 3.0 or something...

But as you said it will install the latest one i.e. 4.2.2.

**Comment by bluca** [comment]
Yes
