### ISSUE TITLE
zmq::context_t and zmq::socket_t easy to convert to void* ,hard to turn it back

### ISSUE THREAD

**Issue by aeiouzy** [zeromq/cppzmq#167]
If there's a function(or constructor) that can be set will better,like 
zmq::context_t context;
void* ptr = (void*)context;
context = (zmq::context_t)ptr;

//That's the problem I have when I write this function
DWORD WINAPI worker_routine(void* context);

**Comment by filipebeavis** [comment]
Hi, 

what was the solution?

thx!
