### ISSUE TITLE
ZMQ's asserts execute in release mode

### ISSUE THREAD

**Issue by Fetterless** [zeromq/cppzmq#169]
Hello!

I use zmq in my project which crashes after a long period of time. After debugging it I saw, that the problem is in zmq: all the ZMQ's asserts (zmq_assert, wsa_assert etc) execute in release mode. If I skip them in Visual Studio, application continues run correctly, but without debugger attached it crashes due to reason above.

Also from **err.hpp:**
```
//  This macro works in exactly the same way as the normal assert. It is used
//  in its stead because standard assert on Win32 in broken - it prints nothing
//  when used within the scope of JNI library.
#define zmq_assert(x) \
    do {\
        if (unlikely (!(x))) {\
            fprintf (stderr, "Assertion failed: %s (%s:%d)\n", #x, \
                __FILE__, __LINE__);\
            fflush (stderr);\
            zmq::zmq_abort (#x);\
        }\
    } while (false)
```

>  This macro works in exactly the same way as the normal assert.

But the normal **assert** is replaced by `assert(_Expression)     ((void)0)` as opposed to zmq.

So, the question is: **"should ZMQ's asserts (zmq_assert, wsa_assert etc) execute in release mode"**?
And an extra question: is it safe to implement **normal assert** logic for zmq asserts in my "special zmq build"?

Thanks in advance

**Comment by sigiesec** [comment]
I think this issue does not target cppzmq, but https://github.com/zeromq/libzmq, and should be reopened there.

**Comment by Fetterless** [comment]
Oh, sorry, my bad.
