### ISSUE TITLE
build problems

### ISSUE THREAD

**Issue by RCYajad** [zeromq/cppzmq#173]
I have been able to build libzmq using the libzmq.sln file found in the msvc/vs2017 folder in the directory with visual studio 2017.   Now, I'm following the instructions on how to build libzmq as mentioned here since I need cppzmq to use zmq with c++. However, the compilation always return an error every time I run the command "make -j4 install". It shows this error

![capture](https://user-images.githubusercontent.com/18350570/34465658-c6313bda-eef1-11e7-88e4-3d64c8015579.PNG) 

It also shows an error whenever I try to build cppzmq first. It shows this error
![image](https://user-images.githubusercontent.com/18350570/34465691-63f66b78-eef3-11e7-86ed-92a546162693.png)

**Comment by sigiesec** [comment]
The cygwin build of libzmq seems to be broken, however please raise this issue there: https://github.com/zeromq/libzmq/issues. Unfortunately, there is currently no CI for cygwin, but if you could set that up for libzmq and send a PR, such issues can be caught much earlier :)

The cppzmq issue then is a follow-up problem.

**Comment by sigiesec** [comment]
I fixed this in https://github.com/sigiesec/libzmq/commit/1fbe3fe2367f2370ebb8d40a58fe6417cb7cd5c8, however this probably is not ready for merging, since it will break other OSes.

I am closing this for now, if the problem persists after fixing libzmq, please reopen.
