### ISSUE TITLE
wrong include in cmake

### ISSUE THREAD

**Issue by qsodev** [zeromq/cppzmq#176]
`include(${CMAKE_CURRENT_LIST_DIR}/libzmqPkgConfigFallback.cmake)`
does not exist anymore! It must be: 
`include(${CMAKE_CURRENT_LIST_DIR}/FindZeroMQ.cmake)`

on `cmake install` FindZeroMQ.cmake is installed twice:
1. in `share/cmake/cppzmq`
2. in `share/cmake/libzmq-pkg-config`
Is there a reason for that or is one enough?

**Comment by minrk** [comment]
Sorry, a bit new to cmake. Should be fixed by #178.
