### ISSUE TITLE
Configure error CMake 3.10.2 / MinGw 5.3.0 32bit

### ISSUE THREAD

**Issue by definable** [zeromq/cppzmq#189]
CMake configuration fails.  Unclear to me what leads to the error. 

CMake Error: File H:/_libs/zeromq-4.2.3/ZeroMQConfig.cmake.in does not exist.
CMake Error at C:/Program Files/CMake/share/cmake-3.10/Modules/CMakePackageConfigHelpers.cmake:312 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:992 (configure_package_config_file)

Configuring incomplete, errors occurred!
See also "C:/Users/ ......  /QtCreator-P1XkOA/qtc-cmake-XX2r9vve/CMakeFiles/CMakeOutput.log".
See also "C:/Users/ ...... /QtCreator-P1XkOA/qtc-cmake-XX2r9vve/CMakeFiles/CMakeError.log".

**Comment by sigiesec** [comment]
I don't think this refers to cppzmq, but to https://github.com/zeromq/libzmq? Try building from https://github.com/zeromq/libzmq/archive/v4.2.5.tar.gz

**Comment by definable** [comment]
You are correct. I tried 4.2.5 and this builds without problems.Thanks for your help.-------- Oorspronkelijk bericht --------Onderwerp: Re: [zeromq/cppzmq] Configure error CMake 3.10.2 / MinGw 5.3.0 32bit (#189)Van: Simon Giesecke Aan: zeromq/cppzmq Cc: definable ,Author I don't think this refers to cppzmq, but to https://github.com/zeromq/libzmq? Try building from https://github.com/zeromq/libzmq/archive/v4.2.5.tar.gz

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/zeromq/cppzmq","title":"zeromq/cppzmq","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/zeromq/cppzmq"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sigiesec in #189: I don't think this refers to cppzmq, but to https://github.com/zeromq/libzmq? Try building from https://github.com/zeromq/libzmq/archive/v4.2.5.tar.gz"}],"action":{"name":"View Issue","url":"https://github.com/zeromq/cppzmq/issues/189#issuecomment-378318811"}}}

**Comment by sigiesec** [comment]
Ok, great! I will close this issue then.
