### ISSUE TITLE
How to change the default install directory to mimic custom homebrew package location?

### ISSUE THREAD

**Issue by skaht** [zeromq/cppzmq#193]
To compile the latest version of Monero I need to change the default install from the privileged **/usr/local/include** directory to an unprivileged directory such as **/Users/Scott/usr/local/homebrew/Cellar/cppzmq/4.2.3/include**.  I'm clueless as to how to get a cmake environment to mimic the equivalent of a **configure --prefix=/Users/Scott/usr/local/homebrew/Cellar/cppzmq/4.2.3/include**. Any suggestions would be greatly appreciated.

**Comment by sigiesec** [comment]
Have you tried
```
make DESTDIR=/home/john install
```

**Comment by skaht** [comment]
Overriding DESTDIR seems to work acceptably. For DESTDIR=/home/john example above, the install path is **/home/john/usr/local/include**.

**Comment by sigiesec** [comment]
Good :) I am closing this issue then. Feel free to reopen if you have further issues.
