### ISSUE TITLE
Installation via vcpkg does not allow find_package calls

### ISSUE THREAD

**Issue by michael-hart** [zeromq/cppzmq#206]
Installing the package via [vcpkg](https://github.com/Microsoft/vcpkg) does not include the cmake files expected. Adding this would improve the Windows experience with cppzmq.

The files would be expected under <vcpkg>/installed/<install_type>/share/cppzmq.

**Comment by sigiesec** [comment]
The vcpkg seems to be defined here: https://github.com/Microsoft/vcpkg/tree/master/ports/cppzmq

You should raise an issue in that repo, or create a PR fixing the package definition.
