### ISSUE TITLE
LINK : fatal error LNK1181: cannot open input file 'libzmq-NOTFOUND.obj'

### ISSUE THREAD

**Issue by shadoweye14** [zeromq/cppzmq#241]
Hello, 

I am trying to compile this project using cmake in MSVC15 (VS2017 Enterprise) and running through some troubles. 

I used cmake to generate MSVS project and copied over the libzmq include headers to the cppzmq directory. I also referenced the libzmq bin paths for both static and dynamic libraries (on different tries). I end up getting the same error however. 

```
1>------ Skipped Build: Project: RUN_TESTS, Configuration: Release x64 ------
1>Project not selected to build for this solution configuration 
2>------ Build started: Project: unit_tests, Configuration: Release x64 ------
2>LINK : fatal error LNK1181: cannot open input file 'libzmq-NOTFOUND.obj'
2>Done building project "unit_tests.vcxproj" -- FAILED.
3>------ Build started: Project: ALL_BUILD, Configuration: Release x64 ------
4>------ Skipped Build: Project: INSTALL, Configuration: Release x64 ------
4>Project not selected to build for this solution configuration 
========== Build: 1 succeeded, 1 failed, 3 up-to-date, 2 skipped ==========
```

What am I doing wrong?
Here are the library folders I am adding to 'Library Path' in the Project Properties. 
```
 Directory of X:\installation_banks\ZMQ\libzmq\bin\x64\Release\v141\dynamic

20/05/2018  15:51    <DIR>          .
20/05/2018  15:51    <DIR>          ..
20/05/2018  15:51           457,216 libzmq.dll
20/05/2018  15:51             7,771 libzmq.exp
20/05/2018  15:51            13,170 libzmq.lib
20/05/2018  15:51             2,384 libzmq.log
20/05/2018  15:51         5,394,432 libzmq.pdb
               5 File(s)      5,874,973 bytes
```
```
 Directory of X:\installation_banks\ZMQ\libzmq\bin\x64\Release\v141\static

20/05/2018  15:50    <DIR>          .
20/05/2018  15:50    <DIR>          ..
20/05/2018  15:50        10,853,784 libzmq.lib
20/05/2018  15:50             2,125 libzmq.log
               2 File(s)     10,855,909 bytes
```

I would appreciate any alternate ways of building this on windows that are currently working.

**Comment by sigiesec** [comment]
Please have a look at the appveyor.yml and the before_build step. That's the way it is done in the CI currently.

I am not sure what you are doing differently. Can you include a script or batch file that describes your steps, and the output of the cmake run?

The CI currently only uses a shared libzmq. It should work with a static libzmq as well. Maybe you can add a variant using a static libzmq to appveyor.yml, so it is ensured this works as well and doesn't break?

**Comment by shadoweye14** [comment]
Thanks for the response, let me try out the CI process and get back to you.

**Comment by shadoweye14** [comment]
I already have the LibZMQ project precompiled for all configurations. For the project use below; I am using Release x64 Dynamic. 

So I followed the following steps:

- Cloned a new repo into a directory, copied over the `libzmq-master\bin\x64\Release\v141\dynamic\*` to `cppzmq-master\libzmq\bin\`

- Ran cmake with with the following output 
```
X:\installation_banks\ZMQ\cppzmq-master>cmake . -G "Visual Studio 15 2017 Win64"
-- Detected CPPZMQ Version - 4.3.0
-- The C compiler identification is MSVC 19.13.26132.0
-- The CXX compiler identification is MSVC 19.13.26132.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- cppzmq v4.3.0
-- Configuring done
-- Generating done
-- Build files have been written to: X:/installation_banks/ZMQ/cppzmq-master/tests/googletest
Microsoft (R) Build Engine version 15.6.85.37198 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 25/05/2018 04:58:52.
Project "X:\installation_banks\ZMQ\cppzmq-master\tests\googletest\ALL_BUILD.vcxproj" on node 1 (default targets).
Project "X:\installation_banks\ZMQ\cppzmq-master\tests\googletest\ALL_BUILD.vcxproj" (1) is building "X:\installation_banks\ZMQ\cppzmq-master\tests\googletest\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "x64\Debug\ZERO_CHECK\".
  Creating directory "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\".
InitializeBuildStatus:
  Creating "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  Checking Build System
  CMake does not need to re-run because X:/installation_banks/ZMQ/cppzmq-master/tests/googletest/CMakeFiles/generate.stamp is up-to-date.
FinalizeBuildStatus:
  Deleting file "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
  Touching "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
Done Building Project "X:\installation_banks\ZMQ\cppzmq-master\tests\googletest\ZERO_CHECK.vcxproj" (default targets).
Project "X:\installation_banks\ZMQ\cppzmq-master\tests\googletest\ALL_BUILD.vcxproj" (1) is building "X:\installation_banks\ZMQ\cppzmq-master\tests\googletest\googletest.vcxproj" (3) on node 1 (default targets).
PrepareForBuild:
  Creating directory "x64\Debug\googletest\".
  Creating directory "x64\Debug\googletest\googletest.tlog\".
InitializeBuildStatus:
  Creating "x64\Debug\googletest\googletest.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ComputeCustomBuildOutput:
  Creating directory "X:\installation_banks\ZMQ\cppzmq-master\tests\googletest\googletest-prefix\src\googletest-stamp\Debug\".
  Creating directory "X:\installation_banks\ZMQ\cppzmq-master\tests\googletest\CMakeFiles\Debug\".
CustomBuild:
  Creating directories for 'googletest'
  Building Custom Rule X:/installation_banks/ZMQ/cppzmq-master/tests/googletest/CMakeLists.txt
  CMake does not need to re-run because X:/installation_banks/ZMQ/cppzmq-master/tests/googletest/CMakeFiles/generate.stamp is up-to-date.
  Performing download step (git clone) for 'googletest'
  Cloning into 'googletest-src'...
  Note: checking out 'release-1.8.0'.

  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by performing another checkout.

  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -b with the checkout command again. Example:

    git checkout -b <new-branch-name>

  HEAD is now at ec44c6c Merge pull request #821 from mazong1123/master
  Performing update step for 'googletest'
  No patch step for 'googletest'
  No configure step for 'googletest'
  No build step for 'googletest'
  No install step for 'googletest'
  No test step for 'googletest'
  Completed 'googletest'
FinalizeBuildStatus:
  Deleting file "x64\Debug\googletest\googletest.tlog\unsuccessfulbuild".
  Touching "x64\Debug\googletest\googletest.tlog\googletest.lastbuildstate".
Done Building Project "X:\installation_banks\ZMQ\cppzmq-master\tests\googletest\googletest.vcxproj" (default targets).
PrepareForBuild:
  Creating directory "x64\Debug\ALL_BUILD\".
  Creating directory "x64\Debug\ALL_BUILD\ALL_BUILD.tlog\".
InitializeBuildStatus:
  Creating "x64\Debug\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  Building Custom Rule X:/installation_banks/ZMQ/cppzmq-master/tests/googletest/CMakeLists.txt
  CMake does not need to re-run because X:/installation_banks/ZMQ/cppzmq-master/tests/googletest/CMakeFiles/generate.stamp is up-to-date.
FinalizeBuildStatus:
  Deleting file "x64\Debug\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild".
  Touching "x64\Debug\ALL_BUILD\ALL_BUILD.tlog\ALL_BUILD.lastbuildstate".
Done Building Project "X:\installation_banks\ZMQ\cppzmq-master\tests\googletest\ALL_BUILD.vcxproj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:08.55
-- Found PythonInterp: C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python36_64/python.exe (found version "3.6.3")
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: X:/installation_banks/ZMQ/cppzmq-master
```

- I started the Visual Studio Project using the SLN files and for every project added the path to the `libzmq-master\include` (especially unit_tests). I did the same with the `cppzmq-master\libzmq\bin\` path which I added to Library Directories. 

- Then running the project on MSVS 2017 I get the following error. 
```
1>------ Skipped Build: Project: RUN_TESTS, Configuration: Release x64 ------
1>Project not selected to build for this solution configuration 
2>------ Build started: Project: unit_tests, Configuration: Release x64 ------
2>LINK : fatal error LNK1181: cannot open input file 'libzmq-NOTFOUND.obj'
2>Done building project "unit_tests.vcxproj" -- FAILED.
3>------ Skipped Build: Project: INSTALL, Configuration: Release x64 ------
3>Project not selected to build for this solution configuration 
========== Build: 0 succeeded, 1 failed, 4 up-to-date, 2 skipped ==========
```

**Comment by sigiesec** [comment]
You do not need to rebuild libzmq, but still you must prepare a setup sufficiently similar to what the before_build steps do, in particular
```
cmake --build libzmq-%ZMQ_VER%/build --target install
```

So you say you
> copied over the libzmq-master\bin\x64\Release\v141\dynamic\* to cppzmq-master\libzmq\bin\

CMake's find_package is used to locate a CMake-built libzmq. Did you build libzmq with CMake? On Unix, also other libzmq builds are supported using pkg-config, but under Windows this is the only supported way.

If you do it differently, you must prepare a similar situation by hand.

You can find the documentation of find_package here: https://cmake.org/cmake/help/v3.11/command/find_package.html

In particular, it says:
> The command searches for a file called <name>Config.cmake or <lower-case-name>-config.cmake for each name specified.

It does not directly search for the libzmq DLLs, but the ZeroMQConfig.cmake generated by the libzmq build.

I hope this information helps in solving your build problem!

**Comment by sigiesec** [comment]
FYI: I added a check for this error, and improved the diagnostic output, so it never generates a solution in case of a failure to locate libzmq in #243

**Comment by shadoweye14** [comment]
Thanks for hte progress and the reply @sigiesec. My apologies though I still am unsure as to how to solve this problem. Could you expand on what you meant by `If you do it differently, you must prepare a similar situation by hand.` I compiled libzmq using cmake by generating a VS2017 project and then opened the project in VS and compiled it there. All I ended up with was the project files and the compiled files in the libzmq folder. I tried manually adding the path to `find_library()` in `FindZeroMQ.cmake` however its still unable to locate said libraries. My apologies, I am not used to cmake and how it configures itself completely yet. What are the basic steps I could take to make this work?

**Comment by sigiesec** [comment]
I am not really familiar with the details of how cmake does this either, sorry, but I can share what I know.

The simplest thing is to do as I wrote before and run `cmake --build <dir> --target install` from the command line. This installs the files to C:/Program Files/ZeroMQ. Unfortunately, this seems to be somewhat broken in the released libzmq version, and was only fixed by https://github.com/zeromq/libzmq/pull/3040. If you want to use the released libzmq version, you could patch it with the changes from the PR.

The directory structure looks like this on my machine:
```
/C/Program Files/ZeroMQ/
/C/Program Files/ZeroMQ/bin
/C/Program Files/ZeroMQ/bin/concrt140.dll
/C/Program Files/ZeroMQ/bin/libzmq-v141-mt-gd-4_2_5.dll
/C/Program Files/ZeroMQ/bin/msvcp140.dll
/C/Program Files/ZeroMQ/bin/vcruntime140.dll
/C/Program Files/ZeroMQ/CMake
/C/Program Files/ZeroMQ/CMake/ZeroMQConfig.cmake
/C/Program Files/ZeroMQ/CMake/ZeroMQConfigVersion.cmake
/C/Program Files/ZeroMQ/CMake/ZeroMQTargets-debug.cmake
/C/Program Files/ZeroMQ/CMake/ZeroMQTargets.cmake
/C/Program Files/ZeroMQ/include
/C/Program Files/ZeroMQ/include/zmq.h
/C/Program Files/ZeroMQ/include/zmq_utils.h
/C/Program Files/ZeroMQ/lib
/C/Program Files/ZeroMQ/lib/libzmq-v141-mt-gd-4_2_5.lib
/C/Program Files/ZeroMQ/lib/libzmq-v141-mt-sgd-4_2_5.lib
/C/Program Files/ZeroMQ/lib/pkgconfig
/C/Program Files/ZeroMQ/lib/pkgconfig/libzmq.pc
/C/Program Files/ZeroMQ/share
/C/Program Files/ZeroMQ/share/zmq
/C/Program Files/ZeroMQ/share/zmq/AUTHORS.txt
/C/Program Files/ZeroMQ/share/zmq/COPYING.LESSER.txt
/C/Program Files/ZeroMQ/share/zmq/COPYING.txt
/C/Program Files/ZeroMQ/share/zmq/NEWS.txt
```

It doesn't need to be in C:\Program Files. The list of installation prefixes CMake searchs in is described in the section starting with "The set of installation prefixes is constructed" under https://cmake.org/cmake/help/v3.11/command/find_package.html

When building libzmq, you can also specify a different target installation prefix, as described here: https://cmake.org/cmake/help/v3.11/variable/CMAKE_INSTALL_PREFIX.html

You can probably also construct this directory structure manually, without using cmake install, but I would not advise to do this.

**Comment by sigiesec** [comment]
When building from the VS IDE, you should also have a target "INSTALL", which has the same effect as doing it from the command line.

**Comment by shadoweye14** [comment]
Okay, let me retry the compilation of the project with cmake and get back to you.

**Comment by sigiesec** [comment]
I am not sure what you want to do. If you just want to use cppzmq, and not modify/develop it, it would be sufficient to copy the zmq.hpp and zmq_addon.hpp header files, if you already have a setup for your project, and you are not using cmake for that.

**Comment by shadoweye14** [comment]
Update: Compiling the base libzmq project with cmake, installing it, and then using `-DCMAKE_PREFIX_PATH="C:\Program Files\ZeroMQ"` to build cppzmq worked perfectly for me. Thanks for all the advice 👍
