### ISSUE TITLE
About build the UDP and the ZMQ_BUILD_DRAFT_API and socket type

### ISSUE THREAD

**Issue by albertroger** [zeromq/cppzmq#261]
I just wanna zmq_udp api,the official doc said With udp we can only connect the ZMQ_RADIO socket type.Now i need to use the ZMQ_DISH and ZMQ_RADIO,but they are not fully supported.so,what should i do for building the libzmq? I just know a little bit about the cmake,specificly answer,please,thank you

**Comment by kurdybacha** [comment]
You have to build `libzmq` with drafts enabled. If you use `cmake` I suggest you follow steps in `ci_build.sh` (`libzmq_install()` and `cppzmq_build()`).

**Comment by sigiesec** [comment]
I suspect the problem was solved by the provided information. If not, feel free to reopen.
