### ISSUE TITLE
On the releases and version numbering

### ISSUE THREAD

**Issue by SylvainCorlay** [zeromq/cppzmq#263]
1. The current `CPPZMQ_VERSION` in the source appears to be `4.3.0`. Is there any plan to tag a `4.3.0` version? (I am a user of cppzmq and maintain the conda package. We really need specific tags and releases to update a package version).

2. Given the activity since the last release, I am worried that `4.3.0` might be backward incompatible with `4.2.3`. If it is the case, it would probably be more appropriate to follow SEMVER and make cppzmq 5.0. This would also make it clear that cppzmq has its own versioning independently of zeromq.

cc @kurdybacha @sigiesec @bluca

**Comment by SylvainCorlay** [comment]
Note: Kudos on adding the fallback to pkg-config if zeromq was not build with cmake.

Note: it is not required to set `PKG_CONFIG_USE_CMAKE_PREFIX_PATH` if we require `cmake 3.1` at least. Cmake 3.1 is quite old, so I think that it should be reasonable to do so.

**Comment by bluca** [comment]
I sure hope backward compatibility wasn't broken - @sigiesec any idea?

Regarding CMake, Debian 8 is still maintained for a couple more years and it uses 3.0

**Comment by kurdybacha** [comment]
backward compatibility has not been broken with all the latest activities. We marked some API as deprecated but it is still there and will produce warning only during compilation.

**Comment by sigiesec** [comment]
I just released 4.3.0

As @kurdybacha said, there should be no incompatible changes to non-DRAFT symbols. If there were, only by mistake, and it should be fixed if you find something.

**Comment by SylvainCorlay** [comment]
Thanks @sigiesec I will test with our downstream packages and update the conda-forge cppzmq package!

**Comment by SylvainCorlay** [comment]
It could be interesting to document which versions of `libzmq` are supported, for example in the readme. There could be a table for recent version of cppzmq.

**Comment by sigiesec** [comment]
The README does document this:
* Tested libzmq versions are
** 4.2.0 (without DRAFT API)
** 4.2.5 (with and without DRAFT API)

Other versions are not tested, and so it is difficult to make any statements about them. If someone expressly needs older versions, tests could be added. However, there were some problems with packaging of older versions, which makes it somewhat hard to set up CI for that. Are you interested in any particular other version?

**Comment by SylvainCorlay** [comment]
Just that as I maintain packages, I need to specify ranges for dependencies.

So far, `cppzmq 4.2.3` conda package was pinning on `libzmq 4.2.3`. (Even though the conda package was built with autotools, we produced the cmake config files for it to be found.)

I am doing some housekeeping on the `cppzmq 4.2.3` recipe before updating to 4.3 and was wondering if I could reasonably assume that any `libzmq 4.2.x` was fine.

**Comment by sigiesec** [comment]
Since 4.2.0 and 4.2.5 are tested, I think it is reasonable to assume that 4.2.x all work.

**Comment by sigiesec** [comment]
Ah, well that's for 4.3.0. Before that there were no tests at all, so honestly, I don't know. But for the future we are in a much better situation now :)

**Comment by SylvainCorlay** [comment]
Ok, sounds good!

**Comment by kurdybacha** [comment]
Great release folks.  Thanks!
I have some notes about the changes if you would like to update release notes with more _digestive_ content @sigiesec @bluca . Feel free to modify.

* fixed issues when compiling with C++11
* fixed and improved cmake build (in and out of source builds, `libzmq` discovery, fallback to pkg-config and more)
* updated `README.md` with clear design goals, supported platforms
* official CI support for Linux, MacOS and Windows
* unit tests infrastructure
* test code coverage brought to 77%
* updated code style (more details in .clang-format)

`socket_t`:
* added support for draft ZMQ_SERVER and ZMQ_CLIENT sockets
* added support for draft ZMQ_RADIO and ZMQ_DISH sockets

`poller_t`:
* `poller_t` became thin abstraction layer on `zmq_poller_*`
* functionality with std::function handlers split and moved to a new `active_poller_t` in `zmq_addon.hpp`
* simpler and safer implementation
* made non-copyable, but properly movable
* more consistent and robust error handling
* event type part of handler definition
* fixed a segfault issue when modifying poller_t from a handler
* added `empty` method indicating presence of registered sockets

`context_t`:
* added methods for context options: `setctxopt(int option_, int optval_)` and `int getctxopt(int option_)`

`message_t`: 
* easier construction from iterable type e.g. `std::string`, `std::array`
* added `!=` and `==` operators and `equals` method marked as deprecated 

`multipart_t`:
* added an `operator<<(std::ostream)` to easily print out `multipart_t` content

**Comment by sigiesec** [comment]
Cool, thanks for the release notes! I added this information!

**Comment by SylvainCorlay** [comment]
Thanks! This is all coming together really nicely. I tested 4.3.0 with our software and we did not have any issue. We are also working with folks who are doing packaging for fedora and freebsd and 4.3.0 might be soon packaged for the respective package managers!

**Comment by kurdybacha** [comment]
Great.
Thanks for the feedback @SylvainCorlay
