### ISSUE TITLE
Fix For ARM on debian need add CMAKE line 

### ISSUE THREAD

**Issue by cyntem** [zeromq/cppzmq#272]
It is doesn't build on debian arm (Raspberry pi 3)
I added this line for CMakeLists.txt and everything was build succesfully.
`SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")`

**Comment by sigiesec** [comment]
Following the comment by @QuLogic, I suspect this is resolved. If not, feel free to reopen.
