### ISSUE TITLE
Error buildng on Ubuntu 16.04

### ISSUE THREAD

**Issue by SimonBirrell** [zeromq/cppzmq#273]
Of the two steps in the readme, the first (compile libzmq) worked ok. The second step fails:
```
cd cppzmq/build/
cmake ..

-- Detected CPPZMQ Version - 4.3.1
-- cppzmq v4.3.1
CMake Error at /usr/share/cmake-3.5/Modules/ExternalProject.cmake:1888 (message):
  Could not extract tarball filename from url:

    https://raw.githubusercontent.com/catchorg/Catch2/Catch1.x/single_include/catch.hpp
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/ExternalProject.cmake:2459 (_ep_add_download_command)
  tests/cmake/catch.cmake:3 (ExternalProject_Add)
  tests/CMakeLists.txt:12 (include)


-- Configuring incomplete, errors occurred!
See also "/home/simon/git_projects/cppzmq/build/CMakeFiles/CMakeOutput.log".
```

**Comment by SimonBirrell** [comment]
Thanks!

**Comment by DanielTakeshi** [comment]
@SimonBirrell  @bluca 

I am running into the same issue here with the missing `catch.hpp` file after typing `cmake ..`. I am hoping to be extra clear on the steps necessary to ignore it when continuing with the next command `sudo make -j4 install` ?

For example, here is what I get on my Ubuntu 16.04 machine, where I have the `cppzmq` code installed in a project directory, based on the master branch as of today (i.e., commit bfdc7885b87e0931a561c769b9b1375595cb7abb ):

```
daniel@takeshi:~/gym-cloth/render/ext/cppzmq$ mkdir build
daniel@takeshi:~/gym-cloth/render/ext/cppzmq$ cd build
daniel@takeshi:~/gym-cloth/render/ext/cppzmq/build$ cmake ..
-- Detected CPPZMQ Version - 4.3.1
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cppzmq v4.3.1
CMake Error at /usr/share/cmake-3.5/Modules/ExternalProject.cmake:1888 (message):
  Could not extract tarball filename from url:

    https://raw.githubusercontent.com/catchorg/Catch2/Catch1.x/single_include/catch.hpp
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/ExternalProject.cmake:2459 (_ep_add_download_command)
  tests/cmake/catch.cmake:3 (ExternalProject_Add)
  tests/CMakeLists.txt:13 (include)


-- Configuring incomplete, errors occurred!
See also "/home/daniel/gym-cloth/render/ext/cppzmq/build/CMakeFiles/CMakeOutput.log".
daniel@takeshi:~/gym-cloth/render/ext/cppzmq/build$ sudo make -j4 install
[sudo] password for daniel: 
make: *** No rule to make target 'install'.  Stop.
daniel@takeshi:~/gym-cloth/render/ext/cppzmq/build$
```

Is there a line of code I can remove or some simple step I'm missing to help the `sudo make -j4 install` command work? Apologies if this question sounds basic, I am still new to cmake and relevant concepts.

**Comment by DanielTakeshi** [comment]
Quick follow-up: after the above, I attempted to run `sudo apt install libzmq3-dev` but then ran into the same installation issues.

To also add: I installed and compiled libzmq (using the repository's README) successfully, before trying to install and compile cppzmq.

**Comment by bluca** [comment]
Don't install manually on Ubuntu. It will just cause issues for no reason. Remove anything that you installed manually with make install, and then ```apt-get install libzmq3-dev``` - that will give you lizmq and cppzmq.

**Comment by DanielTakeshi** [comment]
@bluca  Thank you very much for the explanation.

I am using a different Ubuntu 16.04 machine where I didn't install via those build commands. I ran:

```
(py2-clothsim) seita@hermes1:~/gym-cloth$ sudo apt-get install libzmq3-dev
[sudo] password for seita: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  bbswitch-dkms nvidia-prime
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  libzmq3-dev
0 upgraded, 1 newly installed, 0 to remove and 32 not upgraded.
Need to get 282 kB of archives.
After this operation, 1,438 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 libzmq3-dev amd64 4.1.4-7 [282 kB]
Fetched 282 kB in 0s (507 kB/s)     
Selecting previously unselected package libzmq3-dev:amd64.
(Reading database ... 389760 files and directories currently installed.)
Preparing to unpack .../libzmq3-dev_4.1.4-7_amd64.deb ...
Unpacking libzmq3-dev:amd64 (4.1.4-7) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up libzmq3-dev:amd64 (4.1.4-7) ...
(py2-clothsim) seita@hermes1:~/gym-cloth$
```

Just one point of clarification: is there a way to check if I have libzmq and cppzmq installed? For example, I found this GitHub gist: https://gist.github.com/katopz/8b766a5cb0ca96c816658e9407e83d00

which suggests to confirm via:

```
(py2-clothsim) seita@hermes1:~/gym-cloth/render/build$ ldconfig -p | grep zmq
	libzmq.so.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzmq.so.5
(py2-clothsim) seita@hermes1:~/gym-cloth/render/build$ 
```

But does this mean cppzmq is also installed? Or because cppzmq is header-only according to the README, I will not be able to see it with the above command? [I also seem to be missing one piece of output, as the gist suggests having two lines of output from the command.]

**Comment by bluca** [comment]
The headers are in the standard system path /use/include/

**Comment by DanielTakeshi** [comment]
Thanks @bluca and apologies for the delays in responding.

It appears, though, that I do not see a file that resembles `cppzmq.h` in `/usr/include`, for example this is what I see:

```
(py2-clothsim) daniel@takeshi:~/gym-cloth$ ls -lh /usr/include/
total 4.0M
-rw-r--r--  1 root root 7.3K Jan 14  2018 aio.h
-rw-r--r--  1 root root 2.0K Jan 14  2018 aliases.h
-rw-r--r--  1 root root 1.2K Jan 14  2018 alloca.h
-rw-r--r--  1 root root  25K Jan 14  2018 argp.h
-rw-r--r--  1 root root 7.0K Jan 14  2018 argz.h
-rw-r--r--  1 root root 1.7K Jan 14  2018 ar.h
drwxr-xr-x  2 root root 4.0K Feb 15  2018 arpa
drwxr-xr-x  2 root root 4.0K May 15  2018 asm
drwxr-xr-x  2 root root 4.0K May 15  2018 asm-generic
-rw-r--r--  1 root root 3.5K Jan 14  2018 assert.h
drwxr-xr-x  3 root root 4.0K May 15  2018 atk-1.0
drwxr-xr-x  2 root root  12K May 15  2018 atlas
drwxr-xr-x  3 root root 4.0K May 15  2018 at-spi-2.0
drwxr-xr-x  3 root root 4.0K May 15  2018 at-spi2-atk
-rw-r--r--  1 root root 2.4K Nov  7 10:33 autosprintf.h
-rw-r--r--  1 root root 6.1K Apr  4  2016 autotest.h
-rw-r--r--  1 root root 1.4K Jan 14  2018 byteswap.h
drwxr-xr-x  3 root root 4.0K Feb 15  2018 c++
drwxr-xr-x  2 root root 4.0K May 15  2018 cairo
-rw-r--r--  1 root root  21K Aug 22  2014 cblas_f77.h
-rw-r--r--  1 root root  30K Jan  9  2015 cblas.h
-rw-r--r--  1 root root  444 Jan 16  2016 cblas_mangling.h
lrwxrwxrwx  1 root root   12 Oct 30  2015 com_err.h -> et/com_err.h
-rw-r--r--  1 root root 3.6K Jan 14  2018 complex.h
-rw-r--r--  1 root root 2.3K Jan 14  2018 cpio.h
-rw-r--r--  1 root root 2.3K Jan 14  2018 crypt.h
-rw-r--r--  1 root root  12K Jan 14  2018 ctype.h
-rw-r--r--  1 root root 4.6K Sep 18  2015 cuda_stdint.h
-rw-r--r--  1 root root 114K Sep 18  2015 cupti_activity.h
-rw-r--r--  1 root root  23K Sep 18  2015 cupti_callbacks.h
-rw-r--r--  1 root root  44K Sep 18  2015 cupti_driver_cbid.h
-rw-r--r--  1 root root  48K Sep 18  2015 cupti_events.h
-rw-r--r--  1 root root 4.6K Sep 18  2015 cupti.h
-rw-r--r--  1 root root  31K Sep 18  2015 cupti_metrics.h
-rw-r--r--  1 root root 4.0K Sep 18  2015 cupti_nvtx_cbid.h
-rw-r--r--  1 root root 8.0K Sep 18  2015 cupti_result.h
-rw-r--r--  1 root root  25K Sep 18  2015 cupti_runtime_cbid.h
-rw-r--r--  1 root root 3.8K Sep 18  2015 cupti_version.h
drwxr-xr-x  3 root root 4.0K May 15  2018 dbus-1.0

// skipping a bunch of stuff
```

Perhaps it's worth asking around on StackOverflow and other resources to check?

**Comment by DanielTakeshi** [comment]
AH never mind, I had apparently purged it since I was trying to test reinstallation. I did the sudo apt-get install libzmq3-dev again and got this at the end:

```
-rw-r--r--  1 root root  16K Mar  3  2017 zconf.h
-rw-r--r--  1 root root  86K Mar  3  2017 zlib.h
-rw-r--r--  1 root root  17K Mar 15  2016 zmq.h
-rw-r--r--  1 root root  23K Feb 24  2016 zmq.hpp
-rw-r--r--  1 root root  844 Mar 15  2016 zmq_utils.h
```

Still no sign of a cppzmq.h file but at least zmq.h appears ...

**Comment by sigiesec** [comment]
The cppzmq header is zmq.hpp

**Comment by themightyoarfish** [comment]
How does one solve this problem if for some reason one __must__ compile manually? Just saying "don't do it on ubuntu, use the package" is not a solution.

**Comment by themightyoarfish** [comment]
I have solved this by disabling the tests (`CPPZMQ_BUILD_TESTS=OFF`), but this issue should be reopened.

**Comment by greggwon** [comment]
The cmake cppzmq build really should work out of the box.  It should have all the dependencies to build everything it references, especially Catch2, in an empty as well as populated environment.  Otherwise, there's no point in having a cmake build environment if it's not complete.

**Comment by bluca** [comment]
It works out of the box: it's a header, you include it and it works

**Comment by greggwon** [comment]
You are assuming that there is a distribution and that you can get cppzmp-dev installed etc.  If I am on a raw device and need to build cppzmq completely, than that requires the CMake system to be able to build successfully.  In embedded systems, there is no distribution.  There is a kernel and some libraries and toolsets that are minimal.

**Comment by bluca** [comment]
Build what exactly? It's a header...

**Comment by greggwon** [comment]
I also need to build libzmq.

**Comment by greggwon** [comment]
I want to put all of this into a single CMakeLists.txt to build my whole environment.  It has to work straight through so that I can install with a simple git clone and then cmake.   Copying things around manually is not going to work.

**Comment by gummif** [comment]
You can build and install libzmq first, then provide a path to the install location with env var CMAKE_PREFIX_PATH when building cppzmq (see ci workflow as a (complex) example).

**Comment by greggwon** [comment]
Again, it seems rather silly that this is not just working.  Why do all the users of this have to go searching around for solutions to things that can be solved once, in one place?

**Comment by gummif** [comment]
This is cmake, maybe you can use add_subdirectory or something similar in your project to get it working. Otherwise I would suggest a package manager (conan e.g.) for managing dependencies since cmake is not good at that.

**Comment by bluca** [comment]
> Again, it seems rather silly that this is not just working. Why do all the users of this have to go searching around for solutions to things that can be solved once, in one place?

They are already solved once, in one place - the package managers, be they the distro specific ones or forge-specific like conda, conan and so on. If you don't want to use the existing tools/processes, you are free to create your own scripts or makefiles or whatnot to do what you like for your own specific use case.
