### ISSUE TITLE
Can Not Link zmq library on eclipse

### ISSUE THREAD

**Issue by glconceicao** [zeromq/cppzmq#274]
I try use the pyzmq on eclipse but the library can not link on my project.

![image](https://user-images.githubusercontent.com/40598400/48008376-afc56900-e100-11e8-878b-cfaa7073bdf3.png)

how can i fix it???

**Comment by sigiesec** [comment]
This appears to refer to pyzmq rather than cppzmq. I am closing it here, please open an issue in pyzmq.
