### ISSUE TITLE
zmq_proxy incorrect declaration

### ISSUE THREAD

**Issue by ADDubovik** [zeromq/cppzmq#279]
zmq_proxy declaration is incompatible with original declaration (there's should be "const" added).

**Comment by sigiesec** [comment]
I am not sure what you mean, where is the incompatible declaration and where is the original?

**Comment by kurdybacha** [comment]
@sigiesec I believe this is about arguments' constness.
* libzmq:
`int zmq_proxy (const void *frontend, const void *backend, const void *capture);`
* cppzmq has no const arguments:
`inline void proxy(void *frontend, void *backend, void *capture)`

**Comment by sigiesec** [comment]
Hm, the libzmq documentation is wrong, the arguments are not declared const in zmq.h:
https://github.com/zeromq/libzmq/blob/f21bae529e7e62ab51c97375681db89de055c3ed/include/zmq.h#L525

**Comment by ADDubovik** [comment]
Oh, really.
Should I create an issue in libzmq?

**Comment by sigiesec** [comment]
I fixed the documentation: https://github.com/zeromq/libzmq/pull/3422

**Comment by sigiesec** [comment]
I think this issue can the be closed, right?

**Comment by ADDubovik** [comment]
There's also erraneous WEB-documentation (http://api.zeromq.org/4-2:zmq-proxy).

**Comment by sigiesec** [comment]
I don't know if libzmq 4.2.x is still maintained. With the next libzmq release, new 4.3 docs will probably be generated by the maintainers. But this isn't a cppzmq issue.
