### ISSUE TITLE
SIGABRT Error in IOS

### ISSUE THREAD

**Issue by Pixelvision** [zeromq/cppzmq#282]
Hello, I'm using xcode to generate a build for ipad version 9.3. I am using version 4.2.5 of ZMQ. When using the subscribe socket always the SIGABRT error occurs.
Follow the code below.

Obs:  within the method occurs the expected, it picks up the messages. But in return of that of the other class, which calls the pull message that is where error occurs.

vge::String LegacyCommClient::pullMessage() const
{
    vge::String emptyString;
    zmq_msg_t messageSubscribe;
    zmq_msg_init(&messageSubscribe);
    
    if (m_subSock && zmq_msg_recv (&messageSubscribe, m_subSock, 0) > 0)
    {
        // we got something
        vge::String result = "";

		char* response = (char*)zmq_msg_data(&messageSubscribe);
		size_t size = zmq_msg_size(&messageSubscribe);
		if (size > 0)
		{
			unsigned int outLength;
			response = MessageSecurity::getInstance()->decodeMessage(response, (unsigned int) size, outLength);
			zmq_msg_close(&messageSubscribe);
			if (outLength > 0)
			{
				char* tmp = new char[outLength + 1];
				memcpy(tmp, response, outLength);
				tmp[outLength] = 0;
				result = tmp;
				SAFE_DELETE_ARRAY(tmp);
				SAFE_DELETE_ARRAY(response);
			}
		}
        
        return result;
    }
    zmq_msg_close(&messageSubscribe);
    return emptyString;
}

**Comment by Pixelvision** [comment]
Well I made a change in class zmq.h.

Before it was like that: 
typedef struct zmq_msg_t {unsigned char _ [32];} zmq_msg_t;

As observing the size was surpassing the 32 bits, then desid changed the struct to 64 bits and now it works!

Now:
typedef struct zmq_msg_t {unsigned char _ [64];} zmq_msg_t;

**Comment by sigiesec** [comment]
You appear not to use cppzmq, but libzmq directly, right?

You appear to have a mismatching zmq.h (maybe from libzmq 3.x?). The 4.2.5 version looks like this: https://github.com/zeromq/libzmq/blob/v4.2.5/include/zmq.h#L245

**Comment by Pixelvision** [comment]
Yes true, actually the linking of the headers was pointing to an older version of the lib.

Thanks!
