### ISSUE TITLE
Help with socket.bind()

### ISSUE THREAD

**Issue by SweeXordious** [zeromq/cppzmq#287]
Hello, 

I have a problem with the '**socket.bind("tcp://zmq.service.test.consul:*")**;' in the **c++ binding**. i get the following error : 
`terminate called after throwing an instance of 'zmq::error_t'
what():  No such device
Aborted (core dumped)`

'zmq.service.test.consul' is a consul service defined as a dns entry using the 'dnsmasq'.

When i run the '**dig zmq.service.test.consul**' i get : 

`; <<>> DiG 9.10.3-P4-Ubuntu <<>> zmq.service.test.consul
;; global options: +cmd
;; Got answer:

;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47879
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;zmq.service.test.consul.	IN	A

;; ANSWER SECTION:
zmq.service.test.consul. 0	IN	A	192.168.99.101
zmq.service.test.consul. 0	IN	A	192.168.99.102
zmq.service.test.consul. 0	IN	A	192.168.99.100

;; Query time: 2 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Jan 23 23:26:06 UTC 2019
;; MSG SIZE  rcvd: 89`

And i was planning to make zmq listen on that address for any incoming communications from the ip addresses i get from the dig command. 

Thank you.

**Comment by sigiesec** [comment]
You cannot use a host name with bind, you must use the numerical IP address or the device name. If you want to bind to multiple devices, you can call bind multiple times. If you want to bind to all devices, you can use *

**Comment by sigiesec** [comment]
For reference: http://api.zeromq.org/4-2:zmq-tcp

**Comment by sigiesec** [comment]
Have you been able to resolve your issue?

**Comment by SweeXordious** [comment]
> Have you been able to resolve your issue?

fortunately yes. I changed somehow the way i interact with the hosts and it works now... 

Thank you for your help XD
