### ISSUE TITLE
ZMQ_ASSERT execute code in release mode

### ISSUE THREAD

**Issue by jinq0123** [zeromq/cppzmq#29]
#ifndef NDEBUG
  #   define ZMQ_ASSERT(expression) assert(expression)
  #else
  #   define ZMQ_ASSERT(expression) (void)(expression)
  #endif

ZMQ_ASSERT() execute code in release mode.
Should rename it to ZMQ_VERIFY() or change the behavior.

**Comment by xaqq** [comment]
Hello,

While what you say is not incorrect, the naming (and behavior) is coherent with libzmq which also uses `zmq_assert`.
