### ISSUE TITLE
No way to disable DRAFT API when using the git repo

### ISSUE THREAD

**Issue by t-b** [zeromq/cppzmq#291]
Currently when using a git clone of cppzmq there is no way to disable the DRAFT API.

There should be a CMAKE variable which, independently of the existence of `.git`, let the user enable/disable the DRAFT API.

See https://github.com/zeromq/cppzmq/pull/236#discussion_r189455996 and https://github.com/zeromq/cppzmq/blob/663944180fbe8554575b81163f20ad6e9f61fdeb/CMakeLists.txt#L27-L31

**Comment by sigiesec** [comment]
This is already the case, the quoted lines just declare the default value for ENABLE_DRAFTS. You can run cmake with -DENABLE_DRAFTS=OFF to disable.

**Comment by t-b** [comment]
@sigiesec Thanks for the reminder. Works as expected.
