### ISSUE TITLE
socket_t has a context pointer

### ISSUE THREAD

**Issue by gummif** [zeromq/cppzmq#300]
The member variable `ctxptr` of `socket_t` is never used in that class, and wastes space. It is only used in `monitor_t` in the `init` function. I believe a better approach would be to remove `ctxptr` from `socket_t` and require a context to be passed into the constructor and `init` of `monitor_t`, but that's of course a breaking change.

Is there interest in a pull request for adding overloads to `monitor_t` and marking the other functions depending on a context being in `socket_t` as deprecated?

**Comment by sigiesec** [comment]
I think it is acceptable that the context pointer is stored with a socket_t. The additional storage is absolutely negligible relative to all data structures associated with a libzmq. Removing it would open up for misuses, where the context and socket do not match when using a monitor_t.

**Comment by gummif** [comment]
Yes, it's not a significant relative to everything else. I am trying to think of cases where accessing the context of the socket via something like `associated_context()` can be useful, but that probably creates more problems that it solves.
