### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [zeromq/cppzmq#327]
Is there a plan to make a new formal release? There have been quite a number of commits since the 4.3.0 release (and quite a few issues fixed).

**Comment by sigiesec** [comment]
Yes, I can publish a new release in the next week.

**Comment by Mirko-von-Leipzig** [comment]
Great! Thanks for the swift response.

**Comment by sigiesec** [comment]
Sorry, I forgot about that. v4.4.0 is now released, however!
