### ISSUE TITLE
PROXY_STEERABLE not available with version 4.0.4

### ISSUE THREAD

**Issue by pompobit** [zeromq/cppzmq#34]
I think in the last commit there is an error:

at line 63:
# if ZMQ_VERSION >= ZMQ_MAKE_VERSION(4, 0, 4)

I think should be
# if ZMQ_VERSION > ZMQ_MAKE_VERSION(4, 0, 4)

I've installed zmq 4.0.4 and I don't find proxy_steerable, so probably are included in 4.1 only.
At the moment a program including the zmq.hpp and zmq 4.0.4 does not compile

**Comment by sabelo-iris** [comment]
In 4.0.5 zmq.hpp still doesn't work:  fatal error: zmq.hpp: No such file or directory
 #include <zmq.hpp>

**Comment by sabzo** [comment]
In 4.0.5 zmq.hpp still doesn't work: fatal error: zmq.hpp: No such file or directory
#include

**Comment by sigiesec** [comment]
This was fixed by #36
