### ISSUE TITLE
Example Code

### ISSUE THREAD

**Issue by shawnpringle** [zeromq/cppzmq#359]
Your example code doesn't work with the latest release.  Consider changing your example code in your README file to:
`
#include <string>
#include <zmq.hpp>

int main(int argc, char **argv)
{
    zmq::context_t context;
    zmq::socket_t sock(context, zmq::socket_type::push);
    sock.bind("inproc://test");
    sock.send(zmq::buffer(std::string("Hello, world")), zmq::send_flags::dontwait);

    return 0;
}
`

**Comment by gummif** [comment]
Can you tell us what the problem with it is exactly?

**Comment by shawnpringle** [comment]
According to gcc, broken_example.cpp:9:15: error: ‘str_buffer’ is not a member of ‘zmq’     sock.send(zmq::str_buffer("Hello, world"), zmq::send_flags::dontwait);  Sincerely, Shawn Pringle From: Gudmundur AdalsteinssonSent: October 31, 2019 10:35 AMTo: zeromq/cppzmqCc: Shawn Pringle; AuthorSubject: Re: [zeromq/cppzmq] Example Code (#359) Can you tell us what the problem with it is exactly?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by gummif** [comment]
str_buffer is a function that exists on master. You can see an example that works with the latest release (with C++17) in https://github.com/zeromq/cppzmq/tree/v4.4.1

**Comment by shawnpringle** [comment]
Not according to GCC,g++ -std=gnu++17 -c broken_example.cppbroken_example.cpp: In function ‘int main()’:broken_example.cpp:9:15: error: ‘str_buffer’ is not a member of ‘zmq’     sock.send(zmq::str_buffer("Hello, world"), zmq::send_flags::dontwait);               ^ What does grep say?grep str_buffer *.hpp  Hmm... nothing.  It’s a good thing that I can use the C++17 standard.  I suggest you make a fresh checkout from GitHub and rename your current zmq.hpp and zmq_addon.hpp to something else and then try copying the headers from a 4.4.1.  Your example doesn’t work and it seems to me you have an old installations masking the problem. Sincerely, Shawn Pringle From: Gudmundur AdalsteinssonSent: October 31, 2019 12:40 PMTo: zeromq/cppzmqCc: Shawn Pringle; AuthorSubject: Re: [zeromq/cppzmq] Example Code (#359) str_buffer is a function that exists on master. You can see an example that works with the latest release (with C++17) in https://github.com/zeromq/cppzmq/tree/v4.4.1—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by gummif** [comment]
You clearly don't have latest master because it is there https://github.com/zeromq/cppzmq/search?q=str_buffer&unscoped_q=str_buffer it is however not in the latest release.

**Comment by shawnpringle** [comment]
Gudmundur Adalsteinsson, I am indeed using the latest release and not the latest tip of the repository.  It’s up to you and the rest of the development team to decide whether an example that only works with tip should be displayed in the page of the project. Users will tend to install some release rather than tip and an example that doesn’t work reflects badly on a project.  I for one will continue to use cppzmq .Sincerely, Shawn Pringle From: Gudmundur AdalsteinssonSent: November 1, 2019 9:10 AMTo: zeromq/cppzmqCc: Shawn Pringle; AuthorSubject: Re: [zeromq/cppzmq] Example Code (#359) You clearly don't have latest master because it is there https://github.com/zeromq/cppzmq/search?q=str_buffer&unscoped_q=str_buffer it is however not in the latest release.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by sigiesec** [comment]
@shawnpringle I released a new version 4.5.0, so this inconsistency is resolved now. In general, it is practically unavoidable. The master documentation refers to the master. It might be different if we published documentation with the release separately. 

BTW: When responding to GitHub messages by e-mail, please ensure to do so in plain text.
