### ISSUE TITLE
Is it possible to get a global context without creating one?

### ISSUE THREAD

**Issue by kakyoism** [zeromq/cppzmq#360]
My usecases usually involve only one global context.  pyzmq has an API `zmq.Context.instance()` to get the global one, but I couldn't find an equivalent cppzmq API.

Is it possible to have access to a global context without having to creating it explicitly and tracking it?

**Comment by gummif** [comment]
Not with a header only library. You can easily create one yourself with some sort of singleton pattern. E.g. a function in a cpp file that returns reference to a static variable.
