### ISSUE TITLE
Easy way to strip off raw message "envelope"?

### ISSUE THREAD

**Issue by kakyoism** [zeromq/cppzmq#362]
The raw received `zmq::messege_t.str()` comes with the envelope

```
zmq::messate_t [size xxx] ()
```
That requires an extra step in the client code to strip it off to get the payload.
Is there a straightforward way to "receive" the payload only?

**Comment by sigiesec** [comment]
You can access the payload using `zmq::message_t::data()`. `zmq::message_t::str()` is meant for diagnostic/logging purposes.

**Comment by kakyoism** [comment]
@sigiesec Thanks!

**Comment by Chichele** [comment]
> You can access the payload using `zmq::message_t::data()` (and its size via `zmq::message_t::size()`). `zmq::message_t::str()` is meant for diagnostic/logging purposes.

I think this is ridiculous.
A method named str() should not be used like that.

**Comment by sigiesec** [comment]
@kakyoism  #373 now adds a `to_string` method that does what you want.
