### ISSUE TITLE
Unable to find ZEROMQTARGETS.cmake

### ISSUE THREAD

**Issue by TPrabhat** [zeromq/cppzmq#364]
I'm trying to cmake a c++ application and get the following error.

CMake Error at /home/prabhat/miniconda3/share/cmake/ZeroMQ/ZeroMQConfig.cmake:44 (include):
  include could not find load file:

    /home/prabhat/miniconda3/share/cmake/ZeroMQ/ZeroMQTargets.cmake
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/ignition-cmake0/cmake0/FindZeroMQ.cmake:62 (find_package)
  /usr/share/cmake-3.5/Modules/CMakeFindDependencyMacro.cmake:65 (find_package)
  /usr/lib/x86_64-linux-gnu/cmake/ignition-transport4/ignition-transport4-config.cmake:107 (find_dependency)
  /usr/lib/x86_64-linux-gnu/cmake/gazebo/gazebo-config.cmake:197 (find_package)
  CMakeLists.txt:3 (find_package)

and line 44 of cmake is 
if(NOT TARGET libzmq AND NOT TARGET libzmq-static)
  include("${CMAKE_CURRENT_LIST_DIR}/ZeroMQTargets.cmake")

Can anyone tell me how to fix this issue ?
Thank you

**Comment by gummif** [comment]
Is libzmq installed? May be more relevant in https://github.com/zeromq/libzmq ?

**Comment by sigiesec** [comment]
From the information, I also cannot see that this involves cppzmq. If it does, feel free to reopen this with more information on how to reproduce the problem. If it does not, please resort to the libzmq repository as suggested.
