### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by gummif** [zeromq/cppzmq#375]
A new release would be appreciated, especially for fixing the 32bit issue.

**Comment by sigiesec** [comment]
I just released v4.6.0

If you could summarize the changes since v4.5.0, that would be great, I will enter them in the release info then. I think all recent changes were authored by you :)

**Comment by gummif** [comment]
Thanks for that!

Here is a summary:

- New generic algorithms for sending and receiving multipart messages
- New `to_string` and `to_string_view` member functions in `message_t`
- Less surprising behaviour when move assigning `socket_t` and `context_t`
- Return types for `send` and `recv` moved into `zmq` namespace
- Checks for 32/64bit-ness in `cppzmqConfigVersion.cmake` removed

**Comment by sigiesec** [comment]
Thanks a lot, I updated https://github.com/zeromq/cppzmq/releases/tag/v4.6.0 with that information!
