### ISSUE TITLE
SOCKET no longer defined since winsock2.h removed from zmq.h

### ISSUE THREAD

**Issue by Dysl3xik** [zeromq/cppzmq#382]
If you try to build this library with a newer release of ZeroMQ, on a windows box, you get errors because SOCKET can't be resolved in compatability.h. 

This was introduced in this merge I believe: https://github.com/zeromq/libzmq/pull/3681

I will submit a PR that introduces the same fix into this code base as was proposed in that one.

**Comment by sigiesec** [comment]
Sounds good, thank you!

**Comment by Dysl3xik** [comment]
Oops deeply sorry, I meant to post this to https://github.com/zeromq/zmqpp !

**Comment by daravi** [comment]
Hi. I also see this issue (at least with Visual Studio 17). I have to add `winsock2.h` include to `zmq.hpp` before I could compile my consuming project. I am confused why this issue was closed. Is a PR welcomed?
```
#ifdef _WIN32
#include <winsock2.h>
#endif
```

**Comment by jaewooklee93** [comment]
I've encountered same error

@daravi 's solution nicely works.

Also, I'd like to point out `#include` statements should be below `#define NOMINMAX`

```
#ifdef _WIN32
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <WinSock2.h>
#endif
```

Maybe I should open a new issue

**Comment by Dysl3xik** [comment]
Guys I closed it because I was using the other ZeroMQ CPP project and intended to post there. However this project is probably afflicted the same way.

The issue + PR I issued for that library is here https://github.com/zeromq/zmqpp/issues/233 but the fix there was a tad different because they had an aliased socket type.

If you are experiencing the issue on this library you should re-open this issue and do a PR 👍
