### ISSUE TITLE
Some deprecated  libzmq C API( like zmq-ctx-destroy) still used, can it be updated? 

### ISSUE THREAD

**Issue by starx1000** [zeromq/cppzmq#419]
Some deprecated libzmq C API still used in zmq.hpp, can it be updated to new one?.. 
e.g 
http://api.zeromq.org/4-3:zmq-ctx-destroy
This function is deprecated by zmq_ctx_term(3).

in zmq.hpp line 779
```
        int rc;
        do {
            rc = zmq_ctx_destroy(ptr);
        } while (rc == -1 && errno == EINTR);
```

**Comment by gummif** [comment]
It could be done, but those functions do exactly the same thing so there isn't much to gain.

**Comment by starx1000** [comment]
Yes, thanks.  I just wondering about APIs like 
 1.  deprecated APIs have some drawbacks that need to be replaced by new one.
 2.  deprecated APIs will be removed in some newer releases.
If this 2 concerns do not happen and keep it would be have no side effect.

thanks.
