### ISSUE TITLE
Minor release?

### ISSUE THREAD

**Issue by SylvainCorlay** [zeromq/cppzmq#425]
It's been a few months since the last release, and we are currently pinning to a later commit in downstream projects (We rely on https://github.com/zeromq/cppzmq/pull/389 which was merged after the latest).

Are you planning on tagging a patch release some time soon?

**Comment by gummif** [comment]
I would also appreciate a new release. @sigiesec  The current list of changes from the last release is

* Add shutdown() for context_t
* Typesafe context options
* Typesafe socket options
* Better C++ standard detection
* CMake fixes and improvements
* Multipart message encoding and decoding
* Fix (unlikely) UB in message_t constructor
* Improved poll() overloads
* Require non-null handlers to active_poller
* Fix socket move assignment bug
* Deprecate surprising message_t constructor from string literals

**Comment by sigiesec** [comment]
I have release v4.7.0 now. Sorry for the delay! Thanks @gummif for the summary of changes, I copied this over to the release notes!

**Comment by SylvainCorlay** [comment]
Thanks!
