### ISSUE TITLE
Bug: Sometimes ZMQ_CPP17 not defined on MSVC

### ISSUE THREAD

**Issue by serg06** [zeromq/cppzmq#426]
### System:

- Windows 10
- VS 2019 16.6.2
- MSVC
- Using latest C++20 preview

### Issue

Occasionally `ZMQ_CPP17` doesn't get defined so features like `zmq::message_t::to_string_view()` don't work.

### Explanation

This is where `ZMQ_CPP17` is defined:

```
#if (defined(__cplusplus) && __cplusplus >= 201703L) || (defined(_HAS_CXX17) && _HAS_CXX17 == 1)
    #define ZMQ_CPP17
#endif
```

The first check `(defined(__cplusplus) && __cplusplus >= 201703L)` fails because VS doesn't give `__cplusplus` a proper value if you don't set the [/Zc:__cplusplus](https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=vs-2019) compiler flag.

The second check `(defined(_HAS_CXX17) && _HAS_CXX17 == 1)` fails **if the user hasn't included `vcruntime.h` yet**.

### Potential solutions

1. Before the _HAS_CXX17 check, if compiling with MSVC, include `vcruntime.h`.
2. Move `#include <zmq.h>` above the check because `zmq.h` includes `vcruntime.h`.
3. Move all the includes before the check - [that's how nlohmann/json does it](https://github.com/nlohmann/json/blob/master/include/nlohmann/detail/macro_scope.hpp).

### Temporary workarounds

If anyone runs into this issue, just add the [/Zc:__cplusplus](https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=vs-2019) compiler flag.

**Comment by gummif** [comment]
Thanks for that. After some investigation I think we may want to check _MSVC_LANG instead of the _HAS_CXX macros.

**Comment by zyede** [comment]
How did you compile this library for vs2019?，I tried every method but failed to compile

**Comment by gummif** [comment]
If you are having problems you can submit an issue with more details what fails.

**Comment by serg06** [comment]
> How did you compile this library for vs2019?，I tried every method but failed to compile

I did it by adding `#include <vcruntime.h>` above `#include <zmq.h>`.
