### ISSUE TITLE
Issue with dontwait and filter

### ISSUE THREAD

**Issue by slzatz** [zeromq/cppzmq#427]
This may be the intended behavior but I am not sure why.

If filter is non-empty  I am getting no results for the example client pub-sub below when it receives with dontwait.  If I remove dontwait and keep the filter it works as expected and if I remove the filter and use dontwait it works as expected but I never receive any data and appear to only get EAGAIN with a non-empty filter plus dontwait.  Code is below:

```
#include <zmq.hpp>
#include <iostream>
#include <sstream>
int main (int argc, char *argv[])
{    
    zmq::context_t context (1);
    std::cout << "Collecting updates from weather server…\n" << std::endl;    
    zmq::socket_t subscriber (context, ZMQ_SUB);    
    subscriber.connect("tcp://localhost:5556");

    //  Subscribe to zipcode, default is NYC, 10001
    // with filter commented out below, it works with recv dontwait
    // const char *filter = (argc > 1)? argv [1]: "10001 "; 

    const char *filter = "";   //using an empty filter works with dont wait
    subscriber.setsockopt(ZMQ_SUBSCRIBE, filter, strlen (filter));    
   
   while (1) {      
       zmq::message_t update;
       int zipcode, temperature, relhumidity;

       // below only retrieves data if filter is ""
       auto result = subscriber.recv(update, zmq::recv_flags::dontwait);        
        if (!result)  {
            std::cout << "No Data" << std::endl;          
            continue;         
        }   
        std::istringstream iss(static_cast<char*>(update.data())); 
        iss >> zipcode >> temperature >> relhumidity ;          
        std::cout << temperature << std::endl;
  
  return 0;
}
```

**Comment by serg06** [comment]
What happens if you remove this line:

`std::cout << "No Data" << std::endl;`

and add this to the start of your while loop:

`std::this_thread::sleep_for(std::chrono::microseconds(1));`?

**Comment by slzatz** [comment]
That worked.  Thanks.  Happy to close but is there some place this should be documented (or maybe it was obvious).

**Comment by serg06** [comment]
Np. Personally I think this falls under "user error", I think you're good to close.
