### ISSUE TITLE
Anaconda has automatically installed libzmq on win10, do I have to install libzmq by cmake again?

### ISSUE THREAD

**Issue by monchin** [zeromq/cppzmq#428]
Update: I added anaconda to environment path, and this time `ZeroMQ` is found, but another error occurred.
```
CMake Error at tests/CMakeLists.txt:51 (catch_discover_tests):
  Unknown CMake command "catch_discover_tests".
```

--------------------------------------------------------------------------------------------------------------
Hello,  I want to do some IPC between C++ and python, and I found someone suggest [`zeromq`](https://stackoverflow.com/questions/6915191/simple-ipc-between-c-and-python-cross-platform). 

Happily, I found that `zeromq` have been installed when I installed `anaconda`, and I successfully passed python's [`zeromq` example](https://zeromq.org/languages/python/), and I found `libzmq.lib` and `libzmq.dll` in path `C:\Users\myself\anaconda3\Library\lib` and `C:\Users\myself\anaconda3\Library\bin` separately.

So when I began to install `cppzmq`, I thought there was no need to install `libzmq` via cmake anymore, but error occurred:
```
-- CMake libzmq package not found, trying again with pkg-config (normal install of zeromq)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
CMake Error at CMakeLists.txt:21 (message):
  ZeroMQ was not found, neither as a CMake package nor via pkg-config
```
So I'd like to ask, do I have to install `libzmq` via cmake although I have successfully passed python's zmq example?

---------------------------------------------------

**Comment by euripedesrocha** [comment]
As far as I know Anaconda package don´t provide the pkgconfig files. You could check if they are available in your environment with:
```
pkg-config --list-all | grep libzmq
```

I had problems in having both system and anaconda provided libzmq and switched to manual instalation instead of using the provided by Anaconda.

**Comment by gummif** [comment]
You could point to the installed location like so `cmake .. -DZeroMQ_DIR=/usr/local/share/cmake/ZeroMQ`, that is if libzmq has been built with cmake.
