### ISSUE TITLE
cppzmq use pgm appear Protocol not supported! 

### ISSUE THREAD

**Issue by kandr-zg** [zeromq/cppzmq#438]
There was an error using pgm.
terminate called after throwing an instance of 'zmq::error_t'
  what():  Protocol not supported

**Comment by sigiesec** [comment]
This is an issue of the libzmq you are using. Probably it was built without PGM support. cppzmq just passes the endpoint string through to libzmq. Please check your libzmq build and maybe report an issue in #zeromq/libzmq
