### ISSUE TITLE
cppzmq use draft

### ISSUE THREAD

**Issue by kandr-zg** [zeromq/cppzmq#439]
Build with ./configure --enable-drafts to build libzmq.
And in my code zmq_has("draft") return 1.
But I use ZMQ_ROUTER_NOTIFY an error occurred "Use of undeclared identifier 'ZMQ_ROUTER_NOTIFY".
I don't no why?

**Comment by sigiesec** [comment]
This is not specific to cppzmq, since that only passes through the options defined in zmq.h. You still need to define `ZMQ_BUILD_DRAFT_API` when compiling your application, before including zmq.hpp/zmq.h
