### ISSUE TITLE
 CMake libzmq package not found, trying again with pkg-config

### ISSUE THREAD

**Issue by wubo2018** [zeromq/cppzmq#440]
error message like this:

F:\gs\ice\cppbuild>cmake -G "Visual Studio 14 2015" ../cppzmq
-- Detected CPPZMQ Version - 4.7.0
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -
 works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe

-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
 - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMake libzmq package not found, trying again with pkg-config (normal install of zeromq)
-- Found PkgConfig: C:/Strawberry/perl/bin/pkg-config (found version "")
CMake Error at CMakeLists.txt:21 (message):
  ZeroMQ was not found, neither as a CMake package nor via pkg-config

-- Configuring incomplete, errors occurred!
See also "F:/gs/ice/cppbuild/CMakeFiles/CMakeOutput.log".

I  don't install libzmq , only download in my computer  (F:\gs\ice\libzmq),  
who know this probleam?

**Comment by SurnameX** [comment]
I have same question,eventually，You don't need to compile，see
[](https://github.com/zeromq/cppzmq/issues/420#issuecomment-631339813)

**Comment by SurnameX** [comment]
I have same question,eventually，You don't need to compile，see:

https://github.com/zeromq/cppzmq/issues/420#issuecomment-631339813

**Comment by wubo2018** [comment]
I use cmake-gui 



Detected CPPZMQ Version - 4.6.0
CMake libzmq package not found, trying again with pkg-config (normal install of zeromq)
cppzmq v4.6.0
Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE  
CMake Error at tests/CMakeLists.txt:50 (catch_discover_tests):
  Unknown CMake command "catch_discover_tests".


Configuring incomplete, errors occurred!
See also "F:/gs/ice/cppbuild/CMakeFiles/CMakeOutput.log".
See also "F:/gs/ice/cppbuild/CMakeFiles/CMakeError.log".

**Comment by wubo2018** [comment]
[](url)
![image](https://user-images.githubusercontent.com/51027354/92399253-965a3180-f15c-11ea-8255-74f342b71761.png)
