### ISSUE TITLE
Linus: bind pub socket to port already used by reply socket works without any error. 

### ISSUE THREAD

**Issue by afedechko** [zeromq/cppzmq#445]
Hello, 

I faced with the problem that on Linux I'm able to bind to port that is already used by different socket type.

I have an application, let's call i SERVER, that uses two socket: ZMQ_REP and ZMQ_PUB
Once SERVER starts it creates a ZMQ_REP socket and wait for incoming request. I have a logic to protect myself from using port that is already in used by having list of ports I used one by one. If EADDRINUSE exception occurs it tries next port in a list, an so on. Up until success or all ports are being tried. 

So imagine the list has next ports: 5555, 5556, 5557. and ZMQ_REP socket has successfully binded to port 5555. 

Now, incoming request "tells" my SERVER to start additional ZMQ_PUB socket, as, for example, the CLIENT would like to receive notification from the service without a need to request something. 

now SERVER creates additional ZMQ_PUB socket and tries to bind it. 
And here is the problem and inconsistency between Windows and Linux:
On Windows, when ZMQ_PUB tries to bind to port that is used (5555 in current case) - it throws an exception EADDRINUSE, so that my logic catch it and tries to bind to next port in a list. 
On Linux, however, the bind operation for ZMQ_PUB socket succeeds. But Client is not getting anything when it connects to that port. And actually the fact that client is able to connect ZMQ_SUB socket to the port used by ZMQ_REP socket is also a problem, as the exception has to be thrown: ENOCOMPATPROTO

**Comment by gummif** [comment]
Can you provide minimal code to reproduce it?

**Comment by afedechko** [comment]
Sure, will try to come up with a sample

**Comment by afedechko** [comment]
```
#include <zmq.hpp>

void main()
{
	zmq::context_t _context(1);	
	zmq::socket_t _rep_socket(_context, zmq::socket_type::rep);
	try
	{
		_rep_socket.bind("tcp://127.0.0.1:5555");
	}
	catch(const zmq::error_t& e)
	{
		std::cout << "Bind error for REP socket" << e.what();
		return;
	}

	zmq::socket_t _pub_socket(_context, zmq::socket_type::pub);
	try
	{
               // This line throws on Windows (Expected) and doesn't throw on Linux (Not expected) 
		_pub_socket.bind("tcp://127.0.0.1:5555");
	}
	catch(const zmq::error_t& e)
	{
		std::cout << "Bind error for REP socket" << e.what();
		return;
	}
	std::cout << "All succedded";
}
```

**Comment by gummif** [comment]
I tried this on Ubuntu 16 with latest libzmq and got "Bind error for PUB socketAddress already in use". What linux version are you using, and what version of libzmq?
