### ISSUE TITLE
segfault when testing the cppzmq implementation of the zguide Majordomo Protocol example 

### ISSUE THREAD

**Issue by hbalp** [zeromq/cppzmq#45]
When executing the zguide C++ implementation of the Majordomo example in verbose and debug mode, using the cppzmq header file zmq.hpp; a segfault occurs in process ./mdworker,
just after a client has requested a first service to the broker.

It's a bit hard to debug with breakpoints because the code excerpt pointed to by valgrind is frequently executed. So I thank you in advance for your help.

When tracing the memory usage with valgrind, 
I get the following memory error message (extracted from stdout)
_Uninitialised value was created by a heap allocation_, as listed in more details here below:

[004] echo
## 15-03-22 11:03:12 I: sending HEARTBEAT to broker

[000] 
[006] MDPW01
[001] 04
==4784== Conditional jump or move depends on uninitialised value(s)
==4784==    at 0x804ABF1: std::basic_string<unsigned char, std::char_traits<unsigned char>, std::allocator<unsigned char> >::basic_string(unsigned char const_, std::allocator<unsigned char> const&) (char_traits.h:161)
==4784==    by 0x804FE1B: mdwrk::recv(zmsg_&) (zmsg.hpp:71)
==4784==    by 0x8049E9F: main (mdworker.cpp:18)
==4784==  Uninitialised value was created by a heap allocation
==4784==    at 0x402A9AC: operator new(unsigned int, std::nothrow_t const&) (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==4784==    by 0x40A766A: zmq::stream_engine_t::handshake() (stream_engine.cpp:600)
==4784==    by 0x40A840F: zmq::stream_engine_t::in_event() (stream_engine.cpp:257)
==4784==    by 0x40837A8: zmq::epoll_t::loop() (epoll.cpp:166)
==4784==    by 0x40AF90F: thread_routine (thread.cpp:86)
==4784==    by 0x4058F6F: start_thread (pthread_create.c:312)
==4784==    by 0x42C350D: clone (clone.S:129)
==4784== 
15-03-22 11:03:12 I: received message from broker:

lsb_release -a
: Distributor ID:   Ubuntu
: Description:  Ubuntu 14.04.1 LTS
: Release:  14.04
: Codename: trusty
cppzmq version: git commit 67b216681dd4dbc151c3efdc2ce729c0a2d56e26
zeromq version: zeromq-4.1.0-rc1
zguide version: git commit 67a79791ab082b942e1c8ccb2953b10b0727fa66
mdworker.cpp version: commit 0b5b12b9c7dc5c30853adf10e75c500c43258c6e

mdclient log trace: > ./mdclient -v
15-03-22 11:03:17 I: connecting to broker at tcp://localhost:5555...
## 15-03-22 11:03:17 I: send request to 'echo' service:

[006] MDPC01
[004] echo
[011] Hello world

mdworker log traces: > ./valgrind --track-origins=yes ./mdworker -v 2>&1 | tee debug.mdworker.log

==4784== Memcheck, a memory error detector
==4784== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==4784== Using Valgrind-3.10.0.SVN and LibVEX; rerun with -h for copyright info
==4784== Command: ./mdworker -v
==4784== 
15-03-22 11:03:09 I: connecting to broker at tcp://localhost:5555...
## 15-03-22 11:03:09 I: sending READY to broker

[000] 
[006] MDPW01
[001] 01
[004] echo
## 15-03-22 11:03:12 I: sending HEARTBEAT to broker

[000] 
[006] MDPW01
[001] 04
==4784== Conditional jump or move depends on uninitialised value(s)
==4784==    at 0x804ABF1: std::basic_string<unsigned char, std::char_traits<unsigned char>, std::allocator<unsigned char> >::basic_string(unsigned char const_, std::allocator<unsigned char> const&) (char_traits.h:161)
==4784==    by 0x804FE1B: mdwrk::recv(zmsg_&) (zmsg.hpp:71)
==4784==    by 0x8049E9F: main (mdworker.cpp:18)
==4784==  Uninitialised value was created by a heap allocation
==4784==    at 0x402A9AC: operator new(unsigned int, std::nothrow_t const&) (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==4784==    by 0x40A766A: zmq::stream_engine_t::handshake() (stream_engine.cpp:600)
==4784==    by 0x40A840F: zmq::stream_engine_t::in_event() (stream_engine.cpp:257)
==4784==    by 0x40837A8: zmq::epoll_t::loop() (epoll.cpp:166)
==4784==    by 0x40AF90F: thread_routine (thread.cpp:86)
==4784==    by 0x4058F6F: start_thread (pthread_create.c:312)
==4784==    by 0x42C350D: clone (clone.S:129)
==4784== 
## 15-03-22 11:03:12 I: received message from broker:

[000] 
[006] MDPW01
[001] 04
## 15-03-22 11:03:14 I: received message from broker:

[000] 
[006] MDPW01
[001] 04
## 15-03-22 11:03:14 I: sending HEARTBEAT to broker

[000] 
[006] MDPW01
[001] 04
## 15-03-22 11:03:17 I: received message from broker:

[000] 
[006] MDPW01
[001] 04
## 15-03-22 11:03:17 I: sending HEARTBEAT to broker

[000] 
[006] MDPW01
[001] 04
## 15-03-22 11:03:17 I: received message from broker:

[000] 
[006] MDPW01
[001] 02
[000] 
[000] 
[00b] Hello world
mdworker: mdwrkapi.hpp:124: zmsg\* mdwrk::recv(zmsg*&): Assertion `m_reply_to.size()!=0' failed.
==4784== 
==4784== HEAP SUMMARY:
==4784==     in use at exit: 55,634 bytes in 61 blocks
==4784==   total heap usage: 261 allocs, 200 frees, 71,059 bytes allocated
==4784== 
==4784== LEAK SUMMARY:
==4784==    definitely lost: 0 bytes in 0 blocks
==4784==    indirectly lost: 0 bytes in 0 blocks
==4784==      possibly lost: 590 bytes in 14 blocks
==4784==    still reachable: 55,044 bytes in 47 blocks
==4784==         suppressed: 0 bytes in 0 blocks
==4784== Rerun with --leak-check=full to see details of leaked memory
==4784== 
==4784== For counts of detected and suppressed errors, rerun with: -v
==4784== ERROR SUMMARY: 15 errors from 1 contexts (suppressed: 0 from 0)

mdbroker log trace: > ./mdbroker -v
15-03-22 11:03:09 I: MDP broker/0.1.1 is active at tcp://*:5555
## 15-03-22 11:03:10 I: received message:

[009] 64F6-D716
[000] 
[006] MDPW01
[001] 01
[004] echo
15-03-22 11:03:10 I: registering new worker: 64F6-D716
15-03-22 11:03:10 I: received message:
## 15-03-22 11:03:12 I: received message:

[009] 64F6-D716
[000] 
[006] MDPW01
[001] 04
## 15-03-22 11:03:12 I: sending HEARTBEAT to worker

[009] 64F6-D716
[000] 
[006] MDPW01
[001] 04
## 15-03-22 11:03:14 I: sending HEARTBEAT to worker

[009] 64F6-D716
[000] 
[006] MDPW01
[001] 04
## 15-03-22 11:03:14 I: received message:

[009] 64F6-D716
[000] 
[006] MDPW01
[001] 04
## 15-03-22 11:03:17 I: sending HEARTBEAT to worker

[009] 64F6-D716
[000] 
[006] MDPW01
[001] 04
## 15-03-22 11:03:17 I: received message:

[009] 64F6-D716
[000] 
[006] MDPW01
[001] 04
## 15-03-22 11:03:17 I: received message:

[000] 
[000] 
[006] MDPC01
[004] echo
[00b] Hello world
## 15-03-22 11:03:17 I: sending REQUEST to worker

[009] 64F6-D716
[000] 
[006] MDPW01
[001] 02
[000] 
[000] 
[00b] Hello world
## 15-03-22 11:03:20 I: received message:

[000] 
[000] 
[006] MDPC01
[004] echo
[00b] Hello world
## 15-03-22 11:03:22 I: received message:

[000] 
[000] 
[006] MDPC01
[004] echo
[00b] Hello world

**Comment by sigiesec** [comment]
This is not a cppzmq issue, but one of libzmq. If this is still current, consider reopening within https://github.com/zeromq/libzmq/issues
