### ISSUE TITLE
Blocking socket_t::close() for unit testing

### ISSUE THREAD

**Issue by blackliner** [zeromq/cppzmq#454]
Is there a C++ way to have a blocking behavior for `socket_t::close()`? My problem is that sometimes on CI we get binding errors, and we assume it relates to another socket that is still active from a previous test.

C solution would be using zmq_socket_monitor and wait for ZMQ_EVENT_CLOSED (although I have no Idea how that should look like): https://github.com/zeromq/libzmq/issues/2772

**Comment by gummif** [comment]
You mean binding fails with Address already in use? In that case I would suggest for a robust solution to bind with a wildcard port and connect using the address you get with `zmq::sockopt::last_endpoint`.

**Comment by blackliner** [comment]
Cannot use wildcards. I did it with this approach, any obvious drawbacks?
```c++
  zmq::monitor_t mon;
  mon.init( socket, "inproc://monitor", ZMQ_EVENT_CLOSED );
  socket.close();
  mon.check_event( CLOSING_TIMEOUT_MS );
```

**Comment by gummif** [comment]
I'm not really familiar with the monitor class, but if it works I see no drawbacks.

**Comment by blackliner** [comment]
The only thing I am concerned is if this is deterministic behavior. My hope is, that there will **ALWAYS** be `ZMQ_EVENT_CLOSED`, no matter what. Can I safely assume that?
Or might it be possible that after requesting a close
1. no events arrive
2. a different event arrives and `ZMQ_EVENT_CLOSED` does not

**Comment by gummif** [comment]
I'm not sure what guarantees you get, maybe that would be a better question for the libzmq repo.

 But in cppzmq, if it is already closed then there probably not be any event or if the context is shutdown or terminated.

**Comment by blackliner** [comment]
Thank you, I will try to get an answer from the libzmq guys 👍

**Comment by piponazo** [comment]
Hi @blackliner did you find a way to achieve a reproducible behavior in your unit tests? I am facing the same problem and I would like to find a solution for this.

**Comment by blackliner** [comment]
@piponazo sorry, no we stopped using zmq
