### ISSUE TITLE
The send and recv returns true even no connected.

### ISSUE THREAD

**Issue by portsip** [zeromq/cppzmq#46]
Hi, when I use the cppzmq to connect a wrong IP(actually there no ZMQ server bind), the connect function does not trow exception. After then I try to send and received the data, but the functions always returns true! How could I detect the data is sent out and is recv ?

	// connect 
	try
	{
		int linger = 0;
		mZmqSocket->setsockopt(ZMQ_LINGER, &linger, sizeof(linger));
		stringstream ss;
		ss << "tcp://" << mRemoteIP << ":" << mRemotePort;

		mZmqSocket->connect(ss.str().c_str());
	}
	catch (const zmq::error_t& e)
	{
		cout << "Unable to connect ZMQ socket: " << e.what() << endl;
		return rt;
	}

	try
	{
		while (!mZmqSocket->send(req))
		{
			resip::sleepMs(100);
		}
	}

	catch (const zmq::error_t& e)
	{
		cout << "Failed to send request.";
		return rt;
	}

	// recv response
	zmq::message_t response;
	try
	{
		if (mZmqSocket->recv(&response, ZMQ_DONTWAIT))
		{
			cout << "Received data from server: " << (char *)response.data() << endl;
		}
	}
	catch (const zmq::error_t& e)
	{
		cout << "Got error with recv: " << e.what();
		return rt;
	}

The send and recv functions always return true even no a ZMQ server side running!

**Comment by kobolog** [comment]
ZeroMQ establishes connections in background by default, which also means that you will be able to queue messages to be sent while ZeroMQ engine is trying to connect to that nonexistent peer you've specified. Take a look at http://api.zeromq.org/4-0:zmq-setsockopt, specifically options named ZMQ_IMMEDIATE and ZMQ_ROUTER_MANDATORY (if you use ROUTER socket type).
