### ISSUE TITLE
Question: Why is message_t constructor taking std::string disabled for libstdc++ on gcc 5.4?

### ISSUE THREAD

**Issue by themightyoarfish** [zeromq/cppzmq#468]
https://github.com/zeromq/cppzmq/blob/18db4568f9ff1568193d3a496d87bed4bc9ec59e/zmq.hpp#L457

When using older libstdc++ e.g. with gcc 5.4, the definition of `ZMQ_CPP11_PARTIAL` in 
https://github.com/zeromq/cppzmq/blob/18db4568f9ff1568193d3a496d87bed4bc9ec59e/zmq.hpp#L181
causes the constructor to be compiled out.
What is the reason for this?

**Comment by gummif** [comment]
It would be a breaking change when you upgrade to a newer compiler. Creating `message("foo")` (this is marked deprecated) currently creates a message of size 4 with terminating 0. If this would create message of size 3 with pre C++11 compilers it would break when the compiler/C++ gets updated. Which is unfortunate.

A possible workaround that can be supported is add a new CPPZMQ_NO_DEPRECATED flag that would disable all deprecated functions, and allow this constructor taking std::string to be added.

**Comment by themightyoarfish** [comment]
I don't understand, could you clarify which changes between compilers will lead to different behaviour of this constructor?

**Comment by themightyoarfish** [comment]
In that case, should it not still be possible to use this constructor with GCC 5.4, as it supports C++ 11 as well? It seems that not only the compiler version matters, but the standard lib version as well.

**Comment by gummif** [comment]
It is because a more greedy constructor is available for 11 that would break your code when you update (the template for ranges).

**Comment by themightyoarfish** [comment]
I see. And the stdlib version is relevant how?

**Comment by gummif** [comment]
That template is using some sfinae tricks that require full C++11 support.

**Comment by themightyoarfish** [comment]
13
