### ISSUE TITLE
Improve socket comparison operators (needed for Catch2)

### ISSUE THREAD

**Issue by albestro** [zeromq/cppzmq#469]
Reporting here the discussion with the aim to evaluate the best option to improve them.

> There still is a problem involving `socket_ref` and comparison operators, that I quickly workaround (not committed). I'll investigate further and in case I will open an issue to understand the best way to fix it.

Ok, I've just narrowed down the problem. For `socket_ref` a set of comparison operators is defined (starting from [here](https://github.com/zeromq/cppzmq/blob/18db4568f9ff1568193d3a496d87bed4bc9ec59e/zmq.hpp#L2064)), moreover it is possible to implicitly cast a `socket_t` to a `socket_ref` thanks to https://github.com/zeromq/cppzmq/blob/18db4568f9ff1568193d3a496d87bed4bc9ec59e/zmq.hpp#L2186

so, it is possible to use these comparison operators with both types.

But with Catch a problem arose, because `CHECK(sr == s)` passes by `const&` the operands and the cast operator for `const socket_t` is not available.

Unfortunately, I'm not used to the API of the library, so I would have to dig a bit to understand what's better to do (e.g. enabling the `socket_ref` operator by adding `const`). I can commit this proposal, just to see if other problems will come up in CI.

I don't know if you want me to open an issue about this, or if we want to keep it here and solve it directly.

_Originally posted by @albestro in https://github.com/zeromq/cppzmq/issues/466#issuecomment-753471748_

**Comment by albestro** [comment]
@gummif if I get correctly your suggestion in https://github.com/zeromq/cppzmq/pull/466#issuecomment-762177763, the solution would be to implement the different combinations for the various operators.

I was going to quickly implement it, but I'm not really sure that it is the best solution in terms of maintainability.

What do you think about something similar to this? https://github.com/albestro/cppzmq/commit/80914202e44dfbe0b74496333801d8deb2ccc446

**Comment by gummif** [comment]
@albestro Yes that could would (if you use const &).
