### ISSUE TITLE
zmq_ctx_shutdown() is never called

### ISSUE THREAD

**Issue by mfeemster** [zeromq/cppzmq#47]
When using the straight C API, if one has a listening thread that is blocking on a recv() function and the application shuts down, they call `zmq_ctx_shutdown(context)` and it signals the recv() function to exit and shutdown proceeds normally.

However, in the C++ wrapper you have this for the context_t destructor:

```
inline ~context_t ()
{
    close();
}

inline void close()
{
    if (ptr == NULL)
       return;
    int rc = zmq_ctx_destroy (ptr);
    ZMQ_ASSERT (rc == 0);
    ptr = NULL;
}
```

Note that this does not include a call to `zmq_ctx_shutdown()`.

Would it not be better to first call `zmq_ctx_shutdown()` before `zmq_ctx_destroy()`? Without that, the caller has to manually call `zmq_ctx_shutdown()` before the destructor gets called, which sort of detracts from the automatic cleanup that destructors are intended to offer.

Thoughts?

**Comment by kobolog** [comment]
Sounds reasonable to me.

**Comment by mfeemster** [comment]
Thanks. Just be sure that it's consistent with this:

http://zeromq.org/whitepapers:0mq-termination

**Comment by ricnewton** [comment]
zmq_ctx_shutdown is an optional call, you do not need to call it, zmq_ctx_destroy will do the equivalent of what zmq_ctx_shutdown if zmq_ctx_shutdown has not been called.

zmq_ctx_shutdown was introduced to provide a non-blocking way to unblock any other threads that are waiting on zmq socket called during shutdown so you can avoid deadlock with thread destruction.

So as far as I can see, close is doing the correct thing.

**Comment by mfeemster** [comment]
Good points ricnewton, I was unaware of those. I guess it's safe to disregard this thread then.
