### ISSUE TITLE
How to cleanup IPC file from file system

### ISSUE THREAD

**Issue by Pterosaur** [zeromq/cppzmq#471]
The server code is as follow
```c++
zmq::context_t zmq_ctx_;
zmq::socket_t zmq_sock_(zmq_ctx_, zmq::socket_type::rep),
zmq_sock_.bind("ipc:///tmp/zmq")

...

zmq_sock_.unbind("ipc:///tmp/zmq")
```
The server and client can exit without any exception, but I found the ipc file in `/tmp/zmq` hasn't been cleaned. So what is the right way to gracefully exit my process?

**Comment by gummif** [comment]
Maybe a question that is more relevant to the libzmq repo. I at least havent used ipc before so cant answer that.

**Comment by Pterosaur** [comment]
> Maybe a question that is more relevant to the libzmq repo. I at least havent used ipc before so cant answer that.

Thanks for your reply.
