### ISSUE TITLE
Pollitem_t and Socket_ref

### ISSUE THREAD

**Issue by andremmvgabriel** [zeromq/cppzmq#474]
Hello! Hope this message finds you well :)

I'm having an issue understanding how to poll messages using socket refs... I've searched a lot, in the documentation, in other people questions, but I didn't manage to find anything that could help me.

Just to make a brief global view of what I have:

I'm creating 4 different types of custom objects:
1. SocketManager
2. Entity1
3. Entity2
4. Poller

The SocketManager creates all the sockets that exist. As so, it has a vector of zmq::socket_t as an attribute of the class.

Everytime an Entity1 or Entity2 is created, the SocketManager shares the socket that was created for it by a socket_ref, which is stored inside the created Entity.

All the Entities that I want to poll messages from, I send the socket_ref to the Poller, and I save it inside a vector of socket_ref's.

Ok, so this was the most brief I could say what I have without losing your attention ahah

So, moving forward to my issue... To poll messages using the zmq::poll, I need to create a zmq::pollitem_t* array.

From the documentation, a pollitem_t is define as:

```
typedef struct
{
    void //*socket//;
    int //fd//;
    short //events//;
    short //revents//;
} zmq_pollitem_t;
```

As so, a zmq::pollitem_t is filled as: { socket_t, 0, ZMQ_POLLIN, 0 }

If I instead try to do as: { socket_ref, 0, ZMQ_POLLIN, 0 }, compiling gives the error that there in no match for the operator=, which, I believe, a zmq::pollitem_t cannot be created from a socket_ref.

Is this currently a limitation? Or am I doing something wrong?

Thank you so much for the attention.

Best regards,
André Gabriel

**Comment by gummif** [comment]
Looks like you forgot to call sr.handle() to get the raw void* handle of the socket. Hope that helps.

**Comment by andremmvgabriel** [comment]
I was very sure I tested that previously and didn't work... But I have just tested again and worked perfectly... I don't know what happened back then!

Anyway, thank you for the help, and very sorry for bothering...
