### ISSUE TITLE
zmq::recv_flags for receiving multipart messages

### ISSUE THREAD

**Issue by brugr9** [zeromq/cppzmq#479]
The previous 4.3.1 flag ZMQ_RCVMORE is not replaced by any flag,.
E.g., zmq::recv_flags::rcvmore would be nice.

**Comment by gummif** [comment]
That's actually a socket option, see zmq::sockopt::rcvmore (e.g. `socket.get(zmq::sockopt::rcvmore)`).

**Comment by brugr9** [comment]
Thanks for your reply.
Ok, previous cppzmq 4.3.1 based code was receiving multipart messages in two steps by
`socket_t->recv(&topic_, ZMQ_RCVMORE);`
and
`socket_t->recv(&msg_, ZMQ_DONTWAIT);`

With cppzmq 4.3.2 I decided to use zmq::recv_multipart(...)

Solved.
