### ISSUE TITLE
Please tag a release for the c++ bindings

### ISSUE THREAD

**Issue by tomspur** [zeromq/cppzmq#48]
Would it be possible to also add a version to the c++ bindings and cut a release of it?

Then one can better package it for a distribution and maybe find a matching version with the main zeromq library and it always stays in sync with the latest zeromq.

With just one header file, why was it split into a separate git repository without any version information at all? Having it along the zeromq library would simplify this also.

**Comment by denisarnaud** [comment]
+1 

Currently, for instance, the C++ API is no longer packaged for Fedora/CentOS/RedHat. Versionning that C-++ header file would ease the packaging.

**Comment by barjac** [comment]
+1

**Comment by toebbel** [comment]
+1

**Comment by dmiklic** [comment]
+1

**Comment by xaqq** [comment]
Hello, letting you know that we are discussing merging it back into `libzmq`: http://lists.zeromq.org/pipermail/zeromq-dev/2015-June/029097.html

**Comment by dmiklic** [comment]
+100 to that :)

**Comment by jiegec** [comment]
+10086

**Comment by jiegec** [comment]
However this has not done so far.

**Comment by suryanathan** [comment]
+1

**Comment by mrrichardchou** [comment]
+1

**Comment by sunkin351** [comment]
+1

**Comment by vtellier** [comment]
+1

**Comment by 0mp** [comment]
+1

**Comment by bluca** [comment]
tagged 4.2.1 as requested
