### ISSUE TITLE
Can the subscriber recover with epgm connceting？

### ISSUE THREAD

**Issue by mercerme** [zeromq/cppzmq#481]
Here is the problem that if the pub send data too fast of the subscriber is in weak connection, the subscriber will drop data and in my test case, the subscriber won't get data anymore, even though the wireshark shows that there are data caught.

**Comment by mercerme** [comment]
subscriber.set(zmq::sockopt::heartbeat_ivl, 1000);
with this set, the subscriber can recover from the drop but the cannot receive the loss data. Is there any way to get the loss data? since it says that epgm is a reliable transport

**Comment by gummif** [comment]
Try asking in libzmq. But if the sub cant handle the load then messages will be dropped, even for tcp.
