### ISSUE TITLE
Usage of deprecated function zmq_ctx_destroy

### ISSUE THREAD

**Issue by gitdaddy** [zeromq/cppzmq#484]
https://github.com/zeromq/cppzmq/blob/4f111562e7ce23d53bda53748d934ca523d650d7/zmq.hpp#L854

According to the [zmq API](http://api.zeromq.org/master:zmq-ctx-destroy) ``zmq_ctx_destroy`` is deprecated being replaced with ``zmq_ctx_term``.

**Comment by gummif** [comment]
Yes we should probably change that. Those are actually the same function so there is no functional difference between them.
