### ISSUE TITLE
Why not support std::string directly?

### ISSUE THREAD

**Issue by DinoStray** [zeromq/cppzmq#485]
std::string is basically for C++, why not support directly? 
```
change 
send_result_t send(const_buffer buf, send_flags flags = send_flags::none)
to
send_result_t send(const std::string &buf, send_flags flags = send_flags::none)
```

**Comment by gummif** [comment]
This is inspired by asio and the networking TS. Its just a matter of `send(str)` vs `send(zmq::buffer(str))` which is acceptable I think.
