### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by gummif** [zeromq/cppzmq#489]
Can a new version be released with the (minor) changes that have been made?

**Comment by sigiesec** [comment]
We seem to have an issue with one of the builds. I think we need to change it to use pip3.

**Comment by sigiesec** [comment]
I've #491 to fix that. Once that is merged, we can do a new release.

**Comment by albestro** [comment]
Since you are planning a new release, it may be worth considering also #466, which should be in its last stages.

**Comment by gummif** [comment]
v4.8.0 released
