### ISSUE TITLE
VS2008 compiling error

### ISSUE THREAD

**Issue by nguyenvandu083** [zeromq/cppzmq#50]
When I compiling an example of ZeroMQ in VS2008, there is error with zmq.hpp, which I saw there is problem in zmq.hpp file. I saw the CPP11 check which does not include the last function, in which std::vector does not support .data operator in old C++ compiler version.

```
#ifdef ZMQ_CPP11
inline int poll(zmq_pollitem_t const* items, size_t nitems, std::chrono::milliseconds timeout)
{
    return poll(items, nitems, timeout.count() );
}

inline int poll(std::vector<zmq_pollitem_t> const& items, std::chrono::milliseconds timeout)
{
    return poll(items.data(), items.size(), timeout.count() );
}
#endif

inline int poll(std::vector<zmq_pollitem_t> const& items, long timeout_ = -1)
{
    return poll(items.data(), items.size(), timeout_);      
}
```

**Comment by sigiesec** [comment]
@nguyenvandu083 If this issue is still relevant to you, please submit a PR to fix it. We should also add CI with appveyor building with different VS versions.

**Comment by kurdybacha** [comment]
This was fixed some time ago. @sigiesec @bluca can we close it, please?
