### ISSUE TITLE
crash msg.cpp:590 [Assertion failed]

### ISSUE THREAD

**Issue by Boskicl** [zeromq/cppzmq#502]
Running zeromq for our application on a Ubuntu processor for communication purposes we see this error a lot:

"""

Assertion failed: refs_ >= 0 (bundled/zeromq/src/msg.cpp:590)

"""

**Comment by gummif** [comment]
This is in libzmq https://github.com/zeromq/libzmq

**Comment by Boskicl** [comment]
Thank you will take this request there.
