### ISSUE TITLE
compile failed Ubuntu 20.04, gcc 9.3.0

### ISSUE THREAD

**Issue by Thanh-Binh** [zeromq/cppzmq#521]
I try to compile it using cmake, but got errors
home/test/cppzmq/zmq.hpp:2432:18: error: ‘ZMQ_EVENT_HANDSHAKE_FAILED’ was not declared in this scope; did you mean ‘ZMQ_EVENT_BIND_FAILED’?
 2432 |             case ZMQ_EVENT_HANDSHAKE_FAILED:
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  ZMQ_EVENT_BIND_FAILED
/home/test/cppzmq/zmq.hpp:2435:18: error: ‘ZMQ_EVENT_HANDSHAKE_SUCCEED’ was not declared in this scope
 2435 |             case ZMQ_EVENT_HANDSHAKE_SUCCEED:

Any idea?

**Comment by gummif** [comment]
What version of libzmq are you using and is ZMQ_BUILD_DRAFT_API defined?
