### ISSUE TITLE
how to `#include <zmq.h>` ?

### ISSUE THREAD

**Issue by midannii** [zeromq/cppzmq#529]
I want to use zmq of cpp version.
So I used followed example in your github README.

```cpp
#include <stdio.h>
#include <string>
#include "zmq.hpp"
int main()
{
   zmq::context_t context;
   zmq::socket_t socket(context, zmq::socket_type::push);
   socket.bind("tcp://*:5555");
   const std::string_view m = socket.recv()
   socket.send(zmq::buffer(m), zmq::send_flags::dontwait);
}

```

And I also included zmq.hpp.
However, in zmq.hpp int line 36, there is `#include <zmq.h>` and it occurs error like "zmq.hpp file not found".
I don't know how to solve it ;(

**Comment by gummif** [comment]
The dependency libzmq needs to be installed somewhere the compiler finds it.
