### ISSUE TITLE
Build problem VS2013

### ISSUE THREAD

**Issue by BertDeRijck** [zeromq/cppzmq#54]
Hey,
I have build ZeroMq_4.1.3 as static library. When I include the library and the cpp binding file into my project I got the following errors:

> ZmqRSAggregationTripOutput.obj : error LNK2019: unresolved external symbol __imp_zmq_errno referenced in function "public: __cdecl zmq::context_t::context_t(int,int)" (??0context_t@zmq@@QEAA@HH@Z)
> 1>ZmqRSAggregationTripOutput.obj : error LNK2019: unresolved external symbol __imp_zmq_strerror referenced in function "public: virtual char const \* __cdecl zmq::error_t::what(void)const " (?what@error_t@zmq@@UEBAPEBDXZ)
> 1>ZmqRSAggregationTripOutput.obj : error LNK2019: unresolved external symbol __imp_zmq_ctx_new referenced in function "public: __cdecl zmq::context_t::context_t(int,int)" (??0context_t@zmq@@QEAA@HH@Z)
> 1>ZmqRSAggregationTripOutput.obj : error LNK2019: unresolved external symbol __imp_zmq_ctx_set referenced in function "public: __cdecl zmq::context_t::context_t(int,int)" (??0context_t@zmq@@QEAA@HH@Z)
> 1>ZmqRSAggregationTripOutput.obj : error LNK2019: unresolved external symbol __imp_zmq_ctx_destroy referenced in function "public: void __cdecl zmq::context_t::close(void)" (?close@context_t@zmq@@QEAAXXZ)
> 1>ZmqRSAggregationTripOutput.obj : error LNK2019: unresolved external symbol __imp_zmq_msg_init_size referenced in function "public: __cdecl zmq::message_t::message_t(unsigned __int64)" (??0message_t@zmq@@QEAA@_K@Z)
> 1>ZmqRSAggregationTripOutput.obj : error LNK2019: unresolved external symbol __imp_zmq_msg_send referenced in function "public: bool __cdecl zmq::socket_t::send(class zmq::message_t &,int)" (?send@socket_t@zmq@@QEAA_NAEAVmessage_t@2@H@Z)
> 1>ZmqRSAggregationTripOutput.obj : error LNK2019: unresolved external symbol __imp_zmq_msg_close referenced in function "private: void __cdecl ZmqRSAggregationTripOutput::ProduceOutput(char *,unsigned __int64,unsigned __int64)" (?ProduceOutput@ZmqRSAggregationTripOutput@@AEAAXPEAD_K1@Z)
> 1>ZmqRSAggregationTripOutput.obj : error LNK2019: unresolved external symbol __imp_zmq_socket referenced in function "private: void __cdecl zmq::socket_t::init(class zmq::context_t &,int)" (?init@socket_t@zmq@@AEAAXAEAVcontext_t@2@H@Z)
> 1>ZmqRSAggregationTripOutput.obj : error LNK2019: unresolved external symbol __imp_zmq_close referenced in function "public: void __cdecl zmq::socket_t::close(void)" (?close@socket_t@zmq@@QEAAXXZ)
> 1>ZmqRSAggregationTripOutput.obj : error LNK2019: unresolved external symbol __imp_zmq_bind referenced in function "public: void __cdecl zmq::socket_t::bind(char const *)" (?bind@socket_t@zmq@@QEAAXPEBD@Z)

It seemed that it doesn't find the zmq functions in the library that I compiled
 Unused libraries:
1>    D:..\libs\libzmq.lib

How do I make it work?

Bert

**Comment by davidwtf** [comment]
You should define ZMQ_STATIC macro before you include zmq.h.

**Comment by dguder** [comment]
Did the `ZMQ_STATIC` macro fix this issue? I get a bunch of similar errors when I use a static compiled lib. And I defined `ZMQ_STATIC` right before I included `<zmq.hpp>`

**Comment by hintjens** [comment]
Yes, this is due to compiling the library as static (correctly) but then
compiling the calling code to look for a DLL. You must define ZMQ_STATIC
when compiling the application. You can see what this does in zmq.h.

Note there are two patterns of error here. One (can't find symbols
__imp_xxx) is when the library is static, and the app tries DLL calls; the
other is when the library is a DLL and the app is looking for static calls.

**Comment by AberrantWolf** [comment]
So I'm currently experiencing something quite similar. I am building zmq using "libzmq\builds\msvc\build\buildbase.bat vs2015\libzmq.sln 14", which goes through the 2015 project and builds all six targets for both 32 and 64 bit architecture.

Then in my own project, I'm linking paths to "libzmq/bin/x64/Debug/v140/static" and the actual library is libzmq.lib.

Before every call to `#include "zmq.h"` or `#include "zmq.hpp"` I'm calling `#define ZMQ_STATIC`; and I get all these unresolved symbols (__imp_xxx) as though trying to link to a DLL. The solution is generated using cmake, if that matters.

**Comment by sigiesec** [comment]
Closing this issue as it has been inactive for a long time. If the problem persists, consider reopening. However, it seems to be more related to libzmq than to cppzmq.

**Comment by riordant** [comment]
@davidwtf Been searching for this answer for 4 days, thanks.

**Comment by akhilesh-pandey** [comment]
Hello,

I am able to build on win32 without any error but getting following errors while building on x64 type.

1>------ Build started: Project: ZeroMQServer, Configuration: Release x64 ------
1>  ZMQServer.cpp
1>ZMQServer.cpp(258): warning C4018: '<': signed/unsigned mismatch
1>ZMQServer.obj : error LNK2001: unresolved external symbol zmq_bind
1>ZMQServer.obj : error LNK2001: unresolved external symbol zmq_send
1>ZMQServer.obj : error LNK2001: unresolved external symbol zmq_ctx_destroy
1>ZMQServer.obj : error LNK2001: unresolved external symbol zmq_socket
1>ZMQServer.obj : error LNK2001: unresolved external symbol zmq_strerror
1>ZMQServer.obj : error LNK2001: unresolved external symbol zmq_close
1>ZMQServer.obj : error LNK2001: unresolved external symbol zmq_ctx_set
1>ZMQServer.obj : error LNK2001: unresolved external symbol zmq_errno
1>ZMQServer.obj : error LNK2001: unresolved external symbol zmq_ctx_new
1>ZMQServer.obj : error LNK2001: unresolved external symbol zmq_msg_init
1>ZMQServer.obj : error LNK2001: unresolved external symbol zmq_msg_init_size
1>ZMQServer.obj : error LNK2001: unresolved external symbol zmq_msg_data
1>ZMQServer.obj : error LNK2001: unresolved external symbol zmq_msg_send
1>ZMQServer.obj : error LNK2001: unresolved external symbol zmq_msg_size
1>ZMQServer.obj : error LNK2001: unresolved external symbol zmq_msg_recv
1>ZMQServer.obj : error LNK2001: unresolved external symbol zmq_msg_close

I tried the solution mentioned here: -adding #define ZMQ_STATIC before #include <zmq.hpp> but still the problems remain. Someone please guide me in resolving this issue.

**Comment by zipzit** [comment]
So for the original posting with error LNK2019, there sure are a whole lot of potential troubles.  

[Nice reference here... ](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2019?view=msvc-160)

DUMPBIN is a great troubleshooting tool here, available within Visual Studio (View --> Terminal) 

e.g. `$  dumpbin libzmq-mt-4_3_3.lib /headers`     
(This one checks for the 32bit vs 64bit issue...)
