### ISSUE TITLE
Example files outdated

### ISSUE THREAD

**Issue by haferburg** [zeromq/cppzmq#545]
E. g. here https://github.com/zeromq/zmqpp/blob/develop/examples/simple_server.cpp

I'm getting `error C2653: 'zmqpp': is not a class or namespace name`

The examples haven't been updated in 7 years. I suggest you either update or remove them.

**Comment by gummif** [comment]
This is a different (similarly names) library that looks like is not being maintained.

**Comment by haferburg** [comment]
Sorry, must have gotten confused.
