### ISSUE TITLE
'recv' is deprecated: from 4.3.1, use recv taking a reference to message_t and recv_flags clang

### ISSUE THREAD

**Issue by embeddedpenguin** [zeromq/cppzmq#556]
Warning:
```
'recv' is deprecated: from 4.3.1, use recv taking a reference to message_t and recv_flags clang (-Wdeprecated-declarations) [36, 11]
```

Snippet:
```
if (sub.recv(&msg, 0))
{...}
```

Can't really get around this warning, despite using the function with a flags argument like the warning wants.

**Comment by gin-ahirsch** [comment]
"taking a reference" refers to a C++ reference type, as can be seen in the [type signature](https://github.com/zeromq/cppzmq/blob/c170aabf9280f106e4d99c32cbe61fbe2ebadbd3/zmq.hpp#L1991).
Thus `sub.recv(msg)` (removing the `&` operator) should work to get rid of the warning.

**Comment by embeddedpenguin** [comment]
> "taking a reference" refers to a C++ reference type, as can be seen in the [type signature](https://github.com/zeromq/cppzmq/blob/c170aabf9280f106e4d99c32cbe61fbe2ebadbd3/zmq.hpp#L1991). Thus `sub.recv(msg)` (removing the `&` operator) should work to get rid of the warning.

Making this change causes a compilation error:
```
src/main.cpp:42:37: error: no matching function for call to ‘zmq::socket_t::recv(zmq::message_t&, int)’
   42 |                         if (sub.recv(msg_recv, 0))
      |                             ~~~~~~~~^~~~~~~~~~~~~
```

**Comment by embeddedpenguin** [comment]
Also, my signature is different than the one you've referenced.
```
#ifdef ZMQ_CPP11
    ZMQ_DEPRECATED("from 4.3.1, use recv taking a reference to message_t and recv_flags")
#endif
    bool recv(message_t *msg_, int flags_ = 0)
    {
        int nbytes = zmq_msg_recv(msg_->handle(), _handle, flags_);
        if (nbytes >= 0)
            return true;
        if (zmq_errno() == EAGAIN)
            return false;
        throw error_t();
    }
```

I'm compiling with `-std=gnu++11`. My zmq version is 4.6.0.

**Comment by embeddedpenguin** [comment]
Ok I see what's happening. Fixed by adding this:
```
if (sub.recv(msg_recv, zmq::recv_flags(0)))
{}
```
