### ISSUE TITLE
How to correctly set receive timeout

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [zeromq/cppzmq#562]
I am trying to fix a deprecation warning in code using cpzmq, related to setting socket opts and context ops.
I am not an experienced cpp programmer and unfamiliar with a lot of this :-(

I couldn't find docs or a code sample on how to set the received timeout

code was

```
  int timeout = 10000;
  response_puller.setsockopt(ZMQ_RCVTIMEO, &timeout, sizeof(timeout));
```

and now I am trying

```
  response_puller.set(zmq::sockopt::rcvtimeo, &timeout);
```

without much luck. All help appreciated.

**Comment by gummif** [comment]
What about  response_puller.set(zmq::sockopt::rcvtimeo, timeout); ?

**Comment by andrewdavidmackenzie** [comment]
That worked. Looks like the error message was confusing me and I didn't realize it was so obvious.

Sorry for the noise and thanks!
