### ISSUE TITLE
zmq::recv_flags has not been declared

### ISSUE THREAD

**Issue by maziar840** [zeromq/cppzmq#566]
Hi all,

I am trying to run the first example in zguide on a RHEL7.9 machine (which I don't have sudo access to). Our school's IT has installed the latest versions of cppzmq-devel, czmq, czmq-devel and zeromq-devel (zeromq-4.1.4). However, I get the error mentioned in the title.

The problem seems to be the zmq.hpp file which doesn't include `zmq::recv_flags` or `zmq::buffer` etc. So what is happening? Should I ask them to build cppzmq from the source or am I missing something?

**Comment by gummif** [comment]
The latest cppzmq version is 4.8.1, what does it say in the zmq.hpp header?

**Comment by maziar840** [comment]
There is no mention of version in `zmq.hpp`, but there is this in `zmq.h`:

> /*  Version macros for compile-time API version detection                     */
#define ZMQ_VERSION_MAJOR 4
#define ZMQ_VERSION_MINOR 1
#define ZMQ_VERSION_PATCH 4

**Comment by maziar840** [comment]
For those reaching this page in the future, currently the latest version of cppzmq in RHEL7 repo is 4.1.4 and RHEL8 is 4.4. I couldn't run the examples in zguide in any of those because of major API changes in zmq.hpp. Build the latest version from git.
