### ISSUE TITLE
Visual studio 2013 building (another one)

### ISSUE THREAD

**Issue by brucelane** [zeromq/cppzmq#58]
Hello, 
I get this error:
error C2664: 'int zmq_msg_recv(zmq_msg_t *,void *,int)' : cannot convert 'void *' in 'zmq_msg_t *'	t:\zeromq\cppzmq\zmq.hpp	666	1	cpp.hwclient

thank you for any hint

**Comment by brucelane** [comment]
should it be zmq_msg_recv (&addrMsg, s, 0) instead of zmq_msg_recv (s, &addrMsg, 0) ?
do I have to compile as 32bit or 64bit?

**Comment by imnotfromaustralia** [comment]
Hello! I have the same problem too. There's different function signatures:
`zmq_msg_recv (zmq_msg_t *msg, void *s, int flags)`
vs
`zmq_recvmsg (void *s, zmq_msg_t *msg, int flags)`
so I think the solution is to rewrite all func calls to zmq_recvmsg to match the signature

**Comment by xaqq** [comment]
Since a commit addressing the issue has been merge I assume we can close the issue.
Please feel free to reopen if needed.
