### ISSUE TITLE
Call to constructor of 'zmq::message_t' is ambiguous

### ISSUE THREAD

**Issue by L-Super** [zeromq/cppzmq#585]
When I use the following code, I encounter an error
```cpp
const char* str{"hello"};
zmq::message_t m{str};
```

```
Call to constructor of 'zmq::message_t' is ambiguous
```
![image](https://user-images.githubusercontent.com/40905056/203784603-27b3a1d4-c44c-4cc0-aac0-e72fa874811b.png)

It seems that `const string&` and `string_view` are in conflict.

**Comment by sigiesec** [comment]
You need to explicitly cast to std::string_view in the call to the constructor. Or you could just use std::string_view instead of const char* in the first place.

**Comment by L-Super** [comment]
I want to use it as a template function. How can I improve it?
```cpp
template <typename String>
std::string send(String str)
{
//....
zmq::message_t m{str};
socket.send(m, zmq::send_flags::none);
//....
}

int main()
{
//...
send("hello");
}
```

**Comment by gummif** [comment]
Maybe just
```c++
std::string send(std::string_view str)
{
...
}
```
