### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by uyha** [zeromq/cppzmq#596]
Could a new release be created? I would like to have #595 in the library and I am using Conan to import this library, so it’s only possible to use it after there is a new release of this library.

**Comment by uyha** [comment]
@gummif sorry for pinging, but could you consider this issue?

**Comment by gummif** [comment]
Yes, sorry for the delay, a new release is ready: https://github.com/zeromq/cppzmq/releases/tag/v4.10.0
