### ISSUE TITLE
Ubuntu 18.04 runners deprecated

### ISSUE THREAD

**Issue by dietelTiMaMi** [zeromq/cppzmq#616]
The runners for Ubuntu 18.04 are no longer existent on github.
Should the Runners for Ubuntu be removed or updated to Ubuntu 20.04?

Ubuntu 20.04 has no gcc-4.8 and gcc-5 packages anymore but there are packages for gcc-7
so only one of the three runners can be upgraded at a rather low expense.

I already tested this on my fork: https://github.com/dietelTiMaMi/cppzmq/tree/test/updateRunners

**Comment by gummif** [comment]
Thanks, I have a PR where I was working on this. Will try to get that into master today.

**Comment by dietelTiMaMi** [comment]
Closed with https://github.com/zeromq/cppzmq/pull/599
