### ISSUE TITLE
proxy functions should take C++ classes

### ISSUE THREAD

**Issue by gdfast** [zeromq/cppzmq#63]
Currently, the implementations of the `proxy()` and `proxy_steerable()` functions take `void *` arguments just like the C ZMQ API instead of these cppzmq classes (like `zmq::socket_t` for sockets instead of `void *`).

cppzmq ought to do the appropriate accessing/casting work in the proxy functions instead of the caller.

**Comment by szmcdull** [comment]
In Visual C++, I don't need to cast. But in g++, I have to cast `zmq::socket_t` to `void*`. I suppose the c++ binding should avoid such casting?

**Comment by gdfast** [comment]
That's basically what I'm thinking. Especially because the point of zmq.hpp (in my mind) is to replace the ugly/unfortunate `void*` c structs with nice C++ objects. And if the user/developer has created two sockets that he/she wants to proxy, the call ought to be more along the lines of
`zmq::proxy(socket1, socket2)` and not `zmq::proxy((void*) socket1, (void*) socket2)`

(I'm using clang++ to compile for whatever that's worth)

**Comment by gummif** [comment]
Issue has been solved by https://github.com/zeromq/cppzmq/pull/301
