### ISSUE TITLE
Proxy Steerable does not termimate

### ISSUE THREAD

**Issue by sroycode** [zeromq/cppzmq#71]
The following snippet just hangs

```
// g++ -std=c++11 test.cc -lzmq
#include <iostream>
#include <thread>
#include <memory>
#include "./zmq.hpp"

int main() {

zmq::context_t context(1);

std::thread t( [&context]() {
  sleep(2);
  zmq::socket_t conttwo(context,zmq::socket_type::pub);
  conttwo.bind("inproc://control.default");
  conttwo.send("TERMINATE",9);
  std::cerr << "Terminate Fired" << std::endl;
});

try {
  zmq::socket_t frontend(context,zmq::socket_type::router);
  zmq::socket_t backend(context,zmq::socket_type::dealer);
  zmq::socket_t control(context,zmq::socket_type::sub);
  frontend.bind("inproc://frontend.default");
  backend.bind("inproc://backend.default");
  control.connect("inproc://control.default");
  std::cerr << "Proxy Starting" << std::endl;
  zmq::proxy_steerable(
    (void *)frontend,
    (void *)backend,
    nullptr,
    (void *)control
  );
  std::cerr << " Proxy Stopped" << std::endl;
} catch (std::exception& e) {
  std::cerr << " Threw " << e.what() << std::endl;
}
  t.join();
}
```

**Comment by ronigonzalez** [comment]
Hi in your code is missing setsockoption
all subscribers must set setsockopt( ZMQ_SUBSCRIBE, "", 0); this allow the SUB socket receive all messages.

try {
  zmq::socket_t frontend(context,zmq::socket_type::router);
  zmq::socket_t backend(context,zmq::socket_type::dealer);
  zmq::socket_t control(context,zmq::socket_type::sub);
  frontend.bind("inproc://frontend.default");
  backend.bind("inproc://backend.default");
  control.connect("inproc://control.default");
  **control.setsockopt( ZMQ_SUBSCRIBE, "", 0);** 

  std::cerr << "Proxy Starting" << std::endl;
 .....

**Comment by sigiesec** [comment]
I assume the issue has been solved. 
Please feel free to reopen this issue if your problem persists.
