### ISSUE TITLE
How could I store the message_t into a map ?

### ISSUE THREAD

**Issue by pengweichu** [zeromq/cppzmq#73]
Hello I'm new to ZMQ, I have a question, when I use dealer mode, how to store the id after I received then I can send back the response after a while ?

```
while (!isShutdown())
{
    try
    {
        zmq::message_t identity;
        zmq::message_t msg;

        // 10 milliseconds
        zmq::poll(items, 1, 10);
        if (items[0].revents & ZMQ_POLLIN)
        {
            mWorkerSocket.recv(&identity);
            mWorkerSocket.recv(&msg);
        // How to store the identity into a map or list then after a while I can send back a response ?
        }
    }
    catch (std::exception &e)
    {
        (void)e;
        break;
    }
}
```

**Comment by CommanderBubble** [comment]
you could easily add it to a map or vector or any other container by converting it to a string

    std::string identity_string(static_cast<char*>(identity.data()), identity.size());

but you won't know who to send back to inless you store some more information.
though i don't think that this is an 'issue'.

**Comment by sigiesec** [comment]
I assume the question has been answered. Closing this issue.
