### ISSUE TITLE
Memory leak in monitor_t?

### ISSUE THREAD

**Issue by K0n63n** [zeromq/cppzmq#77]
The while loop (in monitor_t::monitor() method) can be aborted at line 700 and 717. If that happens the `zmq_msg_close (&eventMsg);` will never be executed. Couldn't that create a memory leak?

**Comment by sigiesec** [comment]
I assume this issue has been fixed in the meantime. Therefore I close this issue. Feel free to reopen if the issue persists.

**Comment by K0n63n** [comment]
Yes, it appears to be fixed in #134 by a4z@d4da63fed64316e07cea7462e72375de393122dc
