### ISSUE TITLE
non-portable std::exception

### ISSUE THREAD

**Issue by VirgileD** [zeromq/cppzmq#88]
Hello, while compiling with mingw on Win10 and/or gcc on Xunbutun 16 the following error is thrown:
../include/zmq_addon.hpp:225:86: error: no matching function for call to ‘std::exception::exception(const char [51])’
             throw std::exception("Invalid type, size does not match the message size");

I think that the std exception only takes a string constructor in the Windows lib, not in the standard c++.
I just change the std::exception by a std::runtime_error and everything is fine.
Tell me if you agree on the solution, and if you would accept a merge request.

**Comment by bluca** [comment]
I think this was just fixed by: https://github.com/zeromq/cppzmq/pull/87

Could you please pull and try again?

**Comment by VirgileD** [comment]
Oh, it's exactly what I saw and did, so I'm pretty sure it is ok now, you can close.
Tx!!
(As someone else suggest I think in an issue, you should tag a stable release one in a while :-))
