### ISSUE TITLE
Error with zmq::message_t::gets

### ISSUE THREAD

**Issue by TomNash** [zeromq/cppzmq#91]
Getting the following error trying to use the zmq.hpp on a new install. Don't know what change caused the error, I have an older version of the file that works fine.

    /usr/local/include/zmq.hpp: In member function `const char* zmq::message_t::gets (const char*) const':
    /usr/local/include/zmq.hpp:377:53: error: 'property' was not declared in this scope
      const char* value = zmq_msg_gets (&msg, property);

**Comment by bluca** [comment]
This change I'd guess:

https://github.com/zeromq/cppzmq/pull/90

@0mp could you have a look please?

**Comment by TomNash** [comment]
Sorry I can't be more helpful, I just know I the file is a dependency on a system I'm dealing with.

**Comment by 0mp** [comment]
There's a `_` missing in the second `property`. I'm really sorry for that guys. How can I fix it?

**Comment by bluca** [comment]
No problem. Just send another PR to fix it and I'll merge it. Thanks!

**Comment by 0mp** [comment]
@bluca I've tested it this time. Sorry for the inconvenience. Cheers!

**Comment by bluca** [comment]
No problem!
