### ISSUE TITLE
zmq_msg_gets undefined

### ISSUE THREAD

**Issue by JP-11** [zeromq/cppzmq#93]
When I try to built multivero I get an error that "zmq_msg_gets" identifier is not found

**Comment by sqbing** [comment]
same here, building on centos 6.8, libzmq-3.2.5 from epel repo, zmq_msg_gets undefined.

why don't you add binding for zmq_msg_gets not checking zmq library version first?

**Comment by sqbing** [comment]
PR created #103

**Comment by bluca** [comment]
Thanks!
