### ISSUE TITLE
Reduce copy when send

### ISSUE THREAD

**Issue by laplaceyang** [zeromq/cppzmq#95]
if we change the `zmq_send` to `zmq_send_const` in `socket_t::send (const void*, size_t, int)`, we can reduce copy once

[https://github.com/laplaceyang/cppzmq/commit/404b97212b4a8dfd426b5b03a35ee2bd87de3f43](https://github.com/laplaceyang/cppzmq/commit/404b97212b4a8dfd426b5b03a35ee2bd87de3f43)

**Comment by IA-32** [comment]
and also , can we provide a option when use mulitpart_t, to decide use copy or nocopy.

[https://github.com/IA-32/cppzmq/commit/962002ab5deec00e3cc196cb0f2b369c9165d372#diff-a2de2f39ce154b4a0ceb524a62acb4ee](https://github.com/IA-32/cppzmq/commit/962002ab5deec00e3cc196cb0f2b369c9165d372#diff-a2de2f39ce154b4a0ceb524a62acb4ee)
